import mongoose from "mongoose";
import CompanySettings from "../models/CompanySettings.js";
import Lease from "../models/Lease.js";
import { createTenantInvoiceRecord } from "../controllers/propertyController/tenantInvoices.js";

const toObjectId = (v) =>
  mongoose.Types.ObjectId.isValid(String(v || "")) ? new mongoose.Types.ObjectId(String(v)) : null;

// Returns true if today is the day invoices should be generated for a given config.
// effective trigger = billingDay - daysInAdvance (wraps into previous month when needed).
const isTriggerDay = (billingDay, daysInAdvance, today = new Date()) => {
  const bd = Math.max(1, Math.min(28, Number(billingDay) || 1));
  const adv = Math.max(0, Math.min(14, Number(daysInAdvance) || 0));
  const todayDay = today.getDate();
  const triggerDay = bd - adv;

  if (triggerDay >= 1) {
    return todayDay === triggerDay;
  }

  // triggerDay <= 0 means we roll into the previous month's tail
  const prevMonthDays = new Date(today.getFullYear(), today.getMonth(), 0).getDate();
  const effectivePrevDay = prevMonthDays + triggerDay; // e.g. -1 → last day - 1
  return todayDay === effectivePrevDay;
};

// Billing period: invoice is issued TODAY; due date = billing day of the target month.
// When daysInAdvance > 0, the target month is next month (advance invoicing).
const resolveBillingPeriod = (billingDay, daysInAdvance, today = new Date()) => {
  const bd = Math.max(1, Math.min(28, Number(billingDay) || 1));
  const adv = Math.max(0, Math.min(14, Number(daysInAdvance) || 0));

  let year = today.getFullYear();
  let month = today.getMonth(); // 0-indexed

  if (adv > 0) {
    month += 1;
    if (month > 11) { month = 0; year += 1; }
  }

  // invoiceDate = today (avoids the "future invoicing" guard in createTenantInvoiceRecord)
  const invoiceDate = new Date(today.getFullYear(), today.getMonth(), today.getDate());
  // dueDate = billing day of the target month
  const dueDate = new Date(year, month, bd);
  const periodLabel = new Date(year, month, 1).toLocaleDateString("en-GB", { month: "long", year: "numeric" });

  return { invoiceDate, dueDate, year, month, periodLabel };
};

// Process one company. Returns { created, skipped, errors } or null if not trigger day.
const processCompany = async (businessId, settings, today, forceRun = false) => {
  const { billingDay, daysInAdvance } = settings;

  if (!forceRun && !isTriggerDay(billingDay, daysInAdvance, today)) {
    return null; // not today
  }

  const { invoiceDate, dueDate, year, month, periodLabel } = resolveBillingPeriod(
    billingDay,
    daysInAdvance,
    today
  );

  const activeLeases = await Lease.find({
    business: toObjectId(String(businessId)),
    status: "active",
  })
    .select("tenant unit property rentAmount description")
    .lean();

  let created = 0;
  let skipped = 0;
  const errors = [];

  await Promise.all(
    activeLeases.map(async (lease) => {
      if (!lease.tenant || !lease.unit || Number(lease.rentAmount || 0) <= 0) {
        skipped++;
        return;
      }

      // Idempotency key: one invoice per tenant per billing month
      const idempotencyKey = `auto_rent_${String(lease.tenant)}_${year}_${String(month + 1).padStart(2, "0")}`;

      if (!lease.property) {
        skipped++;
        return;
      }

      // Synthetic req so ensureBusinessAccess bypasses the user-company match check
      const systemReq = { user: { isSystemAdmin: true, company: businessId } };

      try {
        await createTenantInvoiceRecord({
          req: systemReq,
          payload: {
            business: String(businessId),
            tenant: String(lease.tenant),
            unit: String(lease.unit),
            property: String(lease.property),
            category: "RENT_CHARGE",
            amount: Number(lease.rentAmount),
            description: `Rent — ${periodLabel}`,
            invoiceDate: invoiceDate.toISOString(),
            dueDate: dueDate.toISOString(),
            idempotencyKey,
            metadata: { autoGenerated: true, billingDay, period: periodLabel },
          },
          options: { skipGL: false },
        });
        created++;
      } catch (err) {
        // idempotency duplicate = already exists this month → skip silently
        if (/idempotencyKey|duplicate key/i.test(String(err?.message || ""))) {
          skipped++;
        } else {
          errors.push({ leaseId: String(lease._id), message: err?.message || String(err) });
        }
      }
    })
  );

  return { created, skipped, errors };
};

// Main entry point. Call with no args from cron (processes all enabled companies).
// Call with a businessId for manual trigger or testing.
// Set forceRun=true to bypass the enabled flag and the trigger-day check (for manual runs).
export const processAutoRentInvoices = async (businessId = null, today = new Date(), { forceRun = false } = {}) => {
  const query = forceRun ? {} : { "autoInvoicing.enabled": true };
  if (businessId) query.company = toObjectId(String(businessId));

  const settingsDocs = await CompanySettings.find(query)
    .select("company autoInvoicing")
    .lean();

  const results = [];

  for (const doc of settingsDocs) {
    const companyId = String(doc.company);
    try {
      const result = await processCompany(companyId, doc.autoInvoicing, today, forceRun);
      if (result === null) continue; // not trigger day

      const summary = `Created ${result.created}, skipped ${result.skipped}, errors ${result.errors.length}`;
      await CompanySettings.updateOne(
        { company: doc.company },
        { $set: { "autoInvoicing.lastRunAt": new Date(), "autoInvoicing.lastRunSummary": summary } }
      );

      results.push({ businessId: companyId, ...result, summary });

      if (result.errors.length) {
        console.error(`[AutoInvoicing] ${companyId} had ${result.errors.length} error(s):`, result.errors);
      }
    } catch (err) {
      console.error(`[AutoInvoicing] Failed for company ${companyId}:`, err?.message || err);
      results.push({ businessId: companyId, created: 0, skipped: 0, errors: [{ message: err?.message }] });
    }
  }

  return results;
};
