import { setPermissionGroupValue } from './accessMatrix';

/**
 * Role presets per module.
 *
 * Each entry:
 *   label         — section heading shown in the UI
 *   colors        — full Tailwind class strings (must be complete, never dynamic)
 *   allPermissions — every {resource, action} this module controls (used to clear before applying)
 *   roles          — keyed role definitions with label, description, grants[]
 */

// ─── Car Wash ─────────────────────────────────────────────────────────────────
const CW = [
  { resource: 'carwash-dashboard',   action: 'view'    },
  { resource: 'carwash-jobs',        action: 'view'    },
  { resource: 'carwash-jobs',        action: 'create'  },
  { resource: 'carwash-jobs',        action: 'update'  },
  { resource: 'carwash-payments',    action: 'view'    },
  { resource: 'carwash-payments',    action: 'record'  },
  { resource: 'carwash-deposits',    action: 'view'    },
  { resource: 'carwash-deposits',    action: 'create'  },
  { resource: 'carwash-deposits',    action: 'update'  },
  { resource: 'carwash-expenses',    action: 'view'    },
  { resource: 'carwash-expenses',    action: 'create'  },
  { resource: 'carwash-expenses',    action: 'update'  },
  { resource: 'carwash-expenses',    action: 'delete'  },
  { resource: 'carwash-services',    action: 'view'    },
  { resource: 'carwash-services',    action: 'manage'  },
  { resource: 'carwash-staff',       action: 'view'    },
  { resource: 'carwash-staff',       action: 'manage'  },
  { resource: 'carwash-reports',     action: 'view'    },
  { resource: 'carwash-commissions', action: 'view'    },
  { resource: 'carwash-commissions', action: 'manage'  },
  { resource: 'carwash-commissions', action: 'pay'     },
  { resource: 'carwash-loyalty',     action: 'view'    },
  { resource: 'carwash-loyalty',     action: 'manage'  },
  { resource: 'carwash-branches',    action: 'view'    },
  { resource: 'carwash-branches',    action: 'manage'  },
  { resource: 'carwash-settings',    action: 'view'    },
  { resource: 'carwash-settings',    action: 'manage'  },
];

// ─── Property Management ──────────────────────────────────────────────────────
const PM = [
  { resource: 'properties',        action: 'view'      },
  { resource: 'properties',        action: 'create'    },
  { resource: 'properties',        action: 'update'    },
  { resource: 'properties',        action: 'delete'    },
  { resource: 'units',             action: 'view'      },
  { resource: 'units',             action: 'create'    },
  { resource: 'units',             action: 'update'    },
  { resource: 'units',             action: 'delete'    },
  { resource: 'tenants',           action: 'view'      },
  { resource: 'tenants',           action: 'create'    },
  { resource: 'tenants',           action: 'update'    },
  { resource: 'tenants',           action: 'terminate' },
  { resource: 'tenants',           action: 'delete'    },
  { resource: 'leases',            action: 'view'      },
  { resource: 'leases',            action: 'create'    },
  { resource: 'leases',            action: 'update'    },
  { resource: 'leases',            action: 'terminate' },
  { resource: 'deposits',          action: 'view'      },
  { resource: 'deposits',          action: 'create'    },
  { resource: 'deposits',          action: 'refund'    },
  { resource: 'takeOnBalances',    action: 'view'      },
  { resource: 'takeOnBalances',    action: 'create'    },
  { resource: 'tenantInvoices',    action: 'view'      },
  { resource: 'tenantInvoices',    action: 'create'    },
  { resource: 'tenantInvoices',    action: 'update'    },
  { resource: 'tenantInvoices',    action: 'reverse'   },
  { resource: 'tenantInvoices',    action: 'delete'    },
  { resource: 'tenantInvoices',    action: 'export'    },
  { resource: 'receipts',          action: 'view'      },
  { resource: 'receipts',          action: 'create'    },
  { resource: 'receipts',          action: 'import'    },
  { resource: 'receipts',          action: 'reverse'   },
  { resource: 'receipts',          action: 'delete'    },
  { resource: 'prepayments',       action: 'view'      },
  { resource: 'prepayments',       action: 'create'    },
  { resource: 'statements',        action: 'view'      },
  { resource: 'statements',        action: 'create'    },
  { resource: 'statements',        action: 'approve'   },
  { resource: 'statements',        action: 'update'    },
  { resource: 'statements',        action: 'send'      },
  { resource: 'statements',        action: 'export'    },
  { resource: 'statements',        action: 'reverse'   },
  { resource: 'statements',        action: 'delete'    },
  { resource: 'pmReports',         action: 'view'      },
  { resource: 'pmReports',         action: 'export'    },
  { resource: 'agedAnalysis',      action: 'view'      },
  { resource: 'agedAnalysis',      action: 'export'    },
  { resource: 'commissionReports', action: 'view'      },
  { resource: 'commissionReports', action: 'export'    },
  { resource: 'taxReports',        action: 'view'      },
  { resource: 'taxReports',        action: 'export'    },
  { resource: 'landlords',         action: 'view'      },
  { resource: 'landlords',         action: 'create'    },
  { resource: 'landlords',         action: 'update'    },
  { resource: 'landlords',         action: 'delete'    },
  { resource: 'commissions',       action: 'view'      },
  { resource: 'commissions',       action: 'create'    },
  { resource: 'commissions',       action: 'process'   },
  { resource: 'maintenances',      action: 'view'      },
  { resource: 'maintenances',      action: 'create'    },
  { resource: 'maintenances',      action: 'update'    },
  { resource: 'maintenances',      action: 'close'     },
  { resource: 'maintenances',      action: 'delete'    },
  { resource: 'inspections',       action: 'view'      },
  { resource: 'inspections',       action: 'create'    },
  { resource: 'inspections',       action: 'update'    },
  { resource: 'inspections',       action: 'close'     },
  { resource: 'inspections',       action: 'delete'    },
  { resource: 'meterReadings',     action: 'view'      },
  { resource: 'meterReadings',     action: 'create'    },
  { resource: 'latePenalties',     action: 'view'      },
  { resource: 'latePenalties',     action: 'process'   },
  { resource: 'propertyExpenses',  action: 'view'      },
  { resource: 'propertyExpenses',  action: 'create'    },
  { resource: 'propertyExpenses',  action: 'update'    },
  { resource: 'propertyExpenses',  action: 'delete'    },
];

// ─── Accounts ─────────────────────────────────────────────────────────────────
const ACC = [
  { resource: 'chartOfAccounts',      action: 'view'     },
  { resource: 'chartOfAccounts',      action: 'create'   },
  { resource: 'chartOfAccounts',      action: 'update'   },
  { resource: 'chartOfAccounts',      action: 'delete'   },
  { resource: 'journals',             action: 'process'  },
  { resource: 'journals',             action: 'reverse'  },
  { resource: 'bankReconciliation',   action: 'view'     },
  { resource: 'bankReconciliation',   action: 'process'  },
  { resource: 'paymentVouchers',      action: 'view'     },
  { resource: 'paymentVouchers',      action: 'process'  },
  { resource: 'paymentVouchers',      action: 'approve'  },
  { resource: 'paymentVouchers',      action: 'reverse'  },
  { resource: 'expenses',             action: 'view'     },
  { resource: 'expenses',             action: 'create'   },
  { resource: 'expenses',             action: 'approve'  },
  { resource: 'expenses',             action: 'update'   },
  { resource: 'expenses',             action: 'delete'   },
  { resource: 'pettyCash',            action: 'view'     },
  { resource: 'pettyCash',            action: 'create'   },
  { resource: 'pettyCash',            action: 'approve'  },
  { resource: 'budgets',              action: 'view'     },
  { resource: 'budgets',              action: 'create'   },
  { resource: 'budgets',              action: 'approve'  },
  { resource: 'fixedAssets',          action: 'view'     },
  { resource: 'fixedAssets',          action: 'create'   },
  { resource: 'fixedAssets',          action: 'depreciate'},
  { resource: 'creditorLedger',       action: 'view'     },
  { resource: 'financialReports',     action: 'view'     },
  { resource: 'financialReports',     action: 'export'   },
  { resource: 'landlordAdvancements', action: 'view'     },
  { resource: 'landlordAdvancements', action: 'create'   },
  { resource: 'standingOrders',       action: 'view'     },
  { resource: 'standingOrders',       action: 'create'   },
  { resource: 'landlordReceipts',     action: 'view'     },
  { resource: 'landlordReceipts',     action: 'create'   },
  { resource: 'landlordReceipts',     action: 'reverse'  },
  { resource: 'landlordPayments',     action: 'view'     },
  { resource: 'landlordPayments',     action: 'process'  },
  { resource: 'landlordPayments',     action: 'export'   },
  { resource: 'processedStatements',  action: 'view'     },
  { resource: 'processedStatements',  action: 'reverse'  },
  { resource: 'processedStatements',  action: 'send'     },
  { resource: 'processedStatements',  action: 'export'   },
];

// ─── Property Sale ────────────────────────────────────────────────────────────
const SALE = [
  { resource: 'saleListings',    action: 'view'   },
  { resource: 'saleListings',    action: 'create' },
  { resource: 'saleListings',    action: 'update' },
  { resource: 'saleListings',    action: 'delete' },
  { resource: 'saleBuyers',      action: 'view'   },
  { resource: 'saleBuyers',      action: 'create' },
  { resource: 'saleBuyers',      action: 'update' },
  { resource: 'saleAgents',      action: 'view'   },
  { resource: 'saleAgents',      action: 'manage' },
  { resource: 'saleOffers',      action: 'view'   },
  { resource: 'saleOffers',      action: 'create' },
  { resource: 'saleOffers',      action: 'approve'},
  { resource: 'saleDeals',       action: 'view'   },
  { resource: 'saleDeals',       action: 'create' },
  { resource: 'saleDeals',       action: 'close'  },
  { resource: 'salePayments',    action: 'view'   },
  { resource: 'salePayments',    action: 'record' },
  { resource: 'saleCommissions', action: 'view'   },
  { resource: 'saleCommissions', action: 'pay'    },
  { resource: 'saleReports',     action: 'view'   },
  { resource: 'saleReports',     action: 'export' },
];

// ─── Human Resource ───────────────────────────────────────────────────────────
const HR = [
  { resource: 'hrEmployees',  action: 'view'      },
  { resource: 'hrEmployees',  action: 'create'    },
  { resource: 'hrEmployees',  action: 'update'    },
  { resource: 'hrEmployees',  action: 'terminate' },
  { resource: 'hrLeave',      action: 'view'      },
  { resource: 'hrLeave',      action: 'create'    },
  { resource: 'hrLeave',      action: 'approve'   },
  { resource: 'hrLeave',      action: 'manage'    },
  { resource: 'hrPayroll',    action: 'view'      },
  { resource: 'hrPayroll',    action: 'run'       },
  { resource: 'hrPayroll',    action: 'approve'   },
  { resource: 'hrPayroll',    action: 'reverse'   },
  { resource: 'hrStatutory',  action: 'view'      },
  { resource: 'hrStatutory',  action: 'process'   },
  { resource: 'hrAppraisals', action: 'view'      },
  { resource: 'hrAppraisals', action: 'create'    },
  { resource: 'hrAppraisals', action: 'complete'  },
  { resource: 'hrReports',    action: 'view'      },
  { resource: 'hrReports',    action: 'export'    },
  { resource: 'hrSetup',      action: 'view'      },
  { resource: 'hrSetup',      action: 'manage'    },
];

// ─── Inventory / POS ──────────────────────────────────────────────────────────
const INV = [
  { resource: 'inv-dashboard',       action: 'view'     },
  { resource: 'inv-locations',       action: 'view'     },
  { resource: 'inv-locations',       action: 'manage'   },
  { resource: 'inv-categories',      action: 'view'     },
  { resource: 'inv-categories',      action: 'manage'   },
  { resource: 'inv-products',        action: 'view'     },
  { resource: 'inv-products',        action: 'create'   },
  { resource: 'inv-products',        action: 'update'   },
  { resource: 'inv-products',        action: 'delete'   },
  { resource: 'inv-suppliers',       action: 'view'     },
  { resource: 'inv-suppliers',       action: 'manage'   },
  { resource: 'inv-purchase-orders', action: 'view'     },
  { resource: 'inv-purchase-orders', action: 'create'   },
  { resource: 'inv-purchase-orders', action: 'receive'  },
  { resource: 'inv-purchase-orders', action: 'cancel'   },
  { resource: 'inv-transfers',       action: 'view'     },
  { resource: 'inv-transfers',       action: 'create'   },
  { resource: 'inv-transfers',       action: 'dispatch' },
  { resource: 'inv-transfers',       action: 'receive'  },
  { resource: 'inv-stock',           action: 'view'     },
  { resource: 'inv-stock',           action: 'adjust'   },
  { resource: 'inv-stock',           action: 'writeoff' },
  { resource: 'inv-tills',           action: 'view'     },
  { resource: 'inv-tills',           action: 'manage'   },
  { resource: 'inv-reports',         action: 'view'     },
  { resource: 'inv-reports',         action: 'export'   },
  { resource: 'pos-terminal',        action: 'view'     },
  { resource: 'pos-terminal',        action: 'sell'     },
  { resource: 'pos-terminal',        action: 'void'     },
  { resource: 'pos-sessions',        action: 'view'     },
  { resource: 'pos-sessions',        action: 'open'     },
  { resource: 'pos-sessions',        action: 'close'    },
  { resource: 'pos-sales',           action: 'view'     },
  { resource: 'pos-sales',           action: 'export'   },
  { resource: 'pos-reports',         action: 'view'     },
];

// ─── Preset definitions ───────────────────────────────────────────────────────
export const MODULE_ROLE_PRESETS = {
  carwash: {
    label: 'Car Wash Role',
    // Full Tailwind class strings — never dynamic to avoid purging
    blockCls:    'border-sky-200 bg-sky-50',
    titleCls:    'text-sky-700',
    activeCls:   'border-sky-500 bg-sky-500 text-white',
    activeDescCls: 'text-sky-100',
    inactiveCls: 'border-sky-200 bg-white text-sky-800 hover:bg-sky-100',
    hintCls:     'text-sky-700/70',
    allPermissions: CW,
    roles: {
      attendant: {
        label: 'Wash Attendant',
        description: 'Dashboard, Jobs (view/add/update), Washboard only',
        grants: [
          { resource: 'carwash-dashboard', action: 'view'   },
          { resource: 'carwash-jobs',      action: 'view'   },
          { resource: 'carwash-jobs',      action: 'create' },
          { resource: 'carwash-jobs',      action: 'update' },
          { resource: 'carwash-services',  action: 'view'   },
          { resource: 'carwash-staff',     action: 'view'   },
          { resource: 'carwash-settings',  action: 'view'   },
        ],
      },
      cashier: {
        label: 'Cashier',
        description: 'Dashboard, view Jobs, record Payments & Deposits, view Loyalty',
        grants: [
          { resource: 'carwash-dashboard', action: 'view'   },
          { resource: 'carwash-jobs',      action: 'view'   },
          { resource: 'carwash-services',  action: 'view'   },
          { resource: 'carwash-staff',     action: 'view'   },
          { resource: 'carwash-settings',  action: 'view'   },
          { resource: 'carwash-payments',  action: 'view'   },
          { resource: 'carwash-payments',  action: 'record' },
          { resource: 'carwash-deposits',  action: 'view'   },
          { resource: 'carwash-deposits',  action: 'create' },
          { resource: 'carwash-loyalty',   action: 'view'   },
        ],
      },
      supervisor: {
        label: 'Supervisor',
        description: 'Attendant + Cashier + record Expenses, view Staff/Reports/Commissions',
        grants: [
          { resource: 'carwash-dashboard',   action: 'view'   },
          { resource: 'carwash-jobs',        action: 'view'   },
          { resource: 'carwash-jobs',        action: 'create' },
          { resource: 'carwash-jobs',        action: 'update' },
          { resource: 'carwash-services',    action: 'view'   },
          { resource: 'carwash-staff',       action: 'view'   },
          { resource: 'carwash-settings',    action: 'view'   },
          { resource: 'carwash-payments',    action: 'view'   },
          { resource: 'carwash-payments',    action: 'record' },
          { resource: 'carwash-deposits',    action: 'view'   },
          { resource: 'carwash-deposits',    action: 'create' },
          { resource: 'carwash-expenses',    action: 'view'   },
          { resource: 'carwash-expenses',    action: 'create' },
          { resource: 'carwash-reports',     action: 'view'   },
          { resource: 'carwash-loyalty',     action: 'view'   },
          { resource: 'carwash-commissions', action: 'view'   },
        ],
      },
      manager: {
        label: 'Manager',
        description: 'Supervisor + approve Expenses, manage Commissions/Loyalty/Staff, view Financials',
        grants: [
          { resource: 'carwash-dashboard',   action: 'view'   },
          { resource: 'carwash-jobs',        action: 'view'   },
          { resource: 'carwash-jobs',        action: 'create' },
          { resource: 'carwash-jobs',        action: 'update' },
          { resource: 'carwash-services',    action: 'view'   },
          { resource: 'carwash-staff',       action: 'view'   },
          { resource: 'carwash-staff',       action: 'manage' },
          { resource: 'carwash-settings',    action: 'view'   },
          { resource: 'carwash-payments',    action: 'view'   },
          { resource: 'carwash-payments',    action: 'record' },
          { resource: 'carwash-deposits',    action: 'view'   },
          { resource: 'carwash-deposits',    action: 'create' },
          { resource: 'carwash-deposits',    action: 'update' },
          { resource: 'carwash-expenses',    action: 'view'   },
          { resource: 'carwash-expenses',    action: 'create' },
          { resource: 'carwash-expenses',    action: 'update' },
          { resource: 'carwash-expenses',    action: 'delete' },
          { resource: 'carwash-reports',     action: 'view'   },
          { resource: 'carwash-commissions', action: 'view'   },
          { resource: 'carwash-commissions', action: 'manage' },
          { resource: 'carwash-commissions', action: 'pay'    },
          { resource: 'carwash-loyalty',     action: 'view'   },
          { resource: 'carwash-loyalty',     action: 'manage' },
          { resource: 'carwash-branches',    action: 'view'   },
        ],
      },
      admin: {
        label: 'Admin / Owner',
        description: 'Full access — all Car Wash permissions',
        grants: CW,
      },
    },
  },

  propertyManagement: {
    label: 'Property Management Role',
    blockCls:    'border-emerald-200 bg-emerald-50',
    titleCls:    'text-emerald-700',
    activeCls:   'border-emerald-600 bg-emerald-600 text-white',
    activeDescCls: 'text-emerald-100',
    inactiveCls: 'border-emerald-200 bg-white text-emerald-800 hover:bg-emerald-50',
    hintCls:     'text-emerald-700/70',
    allPermissions: PM,
    roles: {
      agent: {
        label: 'Property Agent',
        description: 'View properties, units, tenants, leases, receipts & invoices. Log maintenance.',
        grants: [
          { resource: 'properties',    action: 'view'   },
          { resource: 'units',         action: 'view'   },
          { resource: 'tenants',       action: 'view'   },
          { resource: 'leases',        action: 'view'   },
          { resource: 'deposits',      action: 'view'   },
          { resource: 'tenantInvoices',action: 'view'   },
          { resource: 'receipts',      action: 'view'   },
          { resource: 'prepayments',   action: 'view'   },
          { resource: 'maintenances',  action: 'view'   },
          { resource: 'maintenances',  action: 'create' },
          { resource: 'inspections',   action: 'view'   },
          { resource: 'meterReadings', action: 'view'   },
          { resource: 'landlords',     action: 'view'   },
        ],
      },
      propertyManager: {
        label: 'Property Manager',
        description: 'Agent + create/update tenants, leases, receipts, invoices, statements & reports',
        grants: [
          { resource: 'properties',       action: 'view'      },
          { resource: 'properties',       action: 'create'    },
          { resource: 'properties',       action: 'update'    },
          { resource: 'units',            action: 'view'      },
          { resource: 'units',            action: 'create'    },
          { resource: 'units',            action: 'update'    },
          { resource: 'tenants',          action: 'view'      },
          { resource: 'tenants',          action: 'create'    },
          { resource: 'tenants',          action: 'update'    },
          { resource: 'tenants',          action: 'terminate' },
          { resource: 'leases',           action: 'view'      },
          { resource: 'leases',           action: 'create'    },
          { resource: 'leases',           action: 'update'    },
          { resource: 'leases',           action: 'terminate' },
          { resource: 'deposits',         action: 'view'      },
          { resource: 'deposits',         action: 'create'    },
          { resource: 'tenantInvoices',   action: 'view'      },
          { resource: 'tenantInvoices',   action: 'create'    },
          { resource: 'tenantInvoices',   action: 'update'    },
          { resource: 'tenantInvoices',   action: 'export'    },
          { resource: 'receipts',         action: 'view'      },
          { resource: 'receipts',         action: 'create'    },
          { resource: 'prepayments',      action: 'view'      },
          { resource: 'prepayments',      action: 'create'    },
          { resource: 'statements',       action: 'view'      },
          { resource: 'statements',       action: 'create'    },
          { resource: 'statements',       action: 'send'      },
          { resource: 'statements',       action: 'export'    },
          { resource: 'pmReports',        action: 'view'      },
          { resource: 'pmReports',        action: 'export'    },
          { resource: 'landlords',        action: 'view'      },
          { resource: 'commissions',      action: 'view'      },
          { resource: 'maintenances',     action: 'view'      },
          { resource: 'maintenances',     action: 'create'    },
          { resource: 'maintenances',     action: 'update'    },
          { resource: 'maintenances',     action: 'close'     },
          { resource: 'inspections',      action: 'view'      },
          { resource: 'inspections',      action: 'create'    },
          { resource: 'inspections',      action: 'update'    },
          { resource: 'inspections',      action: 'close'     },
          { resource: 'meterReadings',    action: 'view'      },
          { resource: 'meterReadings',    action: 'create'    },
          { resource: 'latePenalties',    action: 'view'      },
          { resource: 'propertyExpenses', action: 'view'      },
          { resource: 'propertyExpenses', action: 'create'    },
        ],
      },
      admin: {
        label: 'Admin / Owner',
        description: 'Full access — all Property Management permissions',
        grants: PM,
      },
    },
  },

  accounts: {
    label: 'Accounts Role',
    blockCls:    'border-teal-200 bg-teal-50',
    titleCls:    'text-teal-700',
    activeCls:   'border-teal-600 bg-teal-600 text-white',
    activeDescCls: 'text-teal-100',
    inactiveCls: 'border-teal-200 bg-white text-teal-800 hover:bg-teal-50',
    hintCls:     'text-teal-700/70',
    allPermissions: ACC,
    roles: {
      clerk: {
        label: 'Accounts Clerk',
        description: 'View chart of accounts, vouchers, expenses, reports — read-only',
        grants: [
          { resource: 'chartOfAccounts',  action: 'view'   },
          { resource: 'paymentVouchers',  action: 'view'   },
          { resource: 'expenses',         action: 'view'   },
          { resource: 'pettyCash',        action: 'view'   },
          { resource: 'budgets',          action: 'view'   },
          { resource: 'fixedAssets',      action: 'view'   },
          { resource: 'creditorLedger',   action: 'view'   },
          { resource: 'financialReports', action: 'view'   },
          { resource: 'bankReconciliation', action: 'view' },
          { resource: 'landlordPayments', action: 'view'   },
          { resource: 'processedStatements', action: 'view'},
          { resource: 'standingOrders',   action: 'view'   },
          { resource: 'landlordReceipts', action: 'view'   },
          { resource: 'landlordAdvancements', action: 'view'},
        ],
      },
      accountant: {
        label: 'Accountant',
        description: 'Clerk + post journals, create expenses/petty cash, record landlord receipts',
        grants: [
          { resource: 'chartOfAccounts',      action: 'view'    },
          { resource: 'journals',             action: 'process' },
          { resource: 'bankReconciliation',   action: 'view'    },
          { resource: 'paymentVouchers',      action: 'view'    },
          { resource: 'paymentVouchers',      action: 'process' },
          { resource: 'expenses',             action: 'view'    },
          { resource: 'expenses',             action: 'create'  },
          { resource: 'pettyCash',            action: 'view'    },
          { resource: 'pettyCash',            action: 'create'  },
          { resource: 'budgets',              action: 'view'    },
          { resource: 'fixedAssets',          action: 'view'    },
          { resource: 'creditorLedger',       action: 'view'    },
          { resource: 'financialReports',     action: 'view'    },
          { resource: 'financialReports',     action: 'export'  },
          { resource: 'landlordAdvancements', action: 'view'    },
          { resource: 'standingOrders',       action: 'view'    },
          { resource: 'landlordReceipts',     action: 'view'    },
          { resource: 'landlordReceipts',     action: 'create'  },
          { resource: 'landlordPayments',     action: 'view'    },
          { resource: 'processedStatements',  action: 'view'    },
          { resource: 'processedStatements',  action: 'export'  },
        ],
      },
      financeManager: {
        label: 'Finance Manager',
        description: 'Accountant + approve vouchers/expenses, reconcile, pay landlords, manage assets',
        grants: [
          { resource: 'chartOfAccounts',      action: 'view'      },
          { resource: 'chartOfAccounts',      action: 'create'    },
          { resource: 'chartOfAccounts',      action: 'update'    },
          { resource: 'journals',             action: 'process'   },
          { resource: 'journals',             action: 'reverse'   },
          { resource: 'bankReconciliation',   action: 'view'      },
          { resource: 'bankReconciliation',   action: 'process'   },
          { resource: 'paymentVouchers',      action: 'view'      },
          { resource: 'paymentVouchers',      action: 'process'   },
          { resource: 'paymentVouchers',      action: 'approve'   },
          { resource: 'expenses',             action: 'view'      },
          { resource: 'expenses',             action: 'create'    },
          { resource: 'expenses',             action: 'approve'   },
          { resource: 'expenses',             action: 'update'    },
          { resource: 'pettyCash',            action: 'view'      },
          { resource: 'pettyCash',            action: 'create'    },
          { resource: 'pettyCash',            action: 'approve'   },
          { resource: 'budgets',              action: 'view'      },
          { resource: 'budgets',              action: 'create'    },
          { resource: 'budgets',              action: 'approve'   },
          { resource: 'fixedAssets',          action: 'view'      },
          { resource: 'fixedAssets',          action: 'create'    },
          { resource: 'fixedAssets',          action: 'depreciate'},
          { resource: 'creditorLedger',       action: 'view'      },
          { resource: 'financialReports',     action: 'view'      },
          { resource: 'financialReports',     action: 'export'    },
          { resource: 'landlordAdvancements', action: 'view'      },
          { resource: 'landlordAdvancements', action: 'create'    },
          { resource: 'standingOrders',       action: 'view'      },
          { resource: 'standingOrders',       action: 'create'    },
          { resource: 'landlordReceipts',     action: 'view'      },
          { resource: 'landlordReceipts',     action: 'create'    },
          { resource: 'landlordReceipts',     action: 'reverse'   },
          { resource: 'landlordPayments',     action: 'view'      },
          { resource: 'landlordPayments',     action: 'process'   },
          { resource: 'landlordPayments',     action: 'export'    },
          { resource: 'processedStatements',  action: 'view'      },
          { resource: 'processedStatements',  action: 'send'      },
          { resource: 'processedStatements',  action: 'export'    },
        ],
      },
      admin: {
        label: 'Admin / Owner',
        description: 'Full access — all Accounts permissions',
        grants: ACC,
      },
    },
  },

  propertySale: {
    label: 'Property Sales Role',
    blockCls:    'border-blue-200 bg-blue-50',
    titleCls:    'text-blue-700',
    activeCls:   'border-blue-600 bg-blue-600 text-white',
    activeDescCls: 'text-blue-100',
    inactiveCls: 'border-blue-200 bg-white text-blue-800 hover:bg-blue-50',
    hintCls:     'text-blue-700/70',
    allPermissions: SALE,
    roles: {
      salesAgent: {
        label: 'Sales Agent',
        description: 'View listings, add/update buyers, create offers, record payments',
        grants: [
          { resource: 'saleListings',  action: 'view'   },
          { resource: 'saleBuyers',    action: 'view'   },
          { resource: 'saleBuyers',    action: 'create' },
          { resource: 'saleBuyers',    action: 'update' },
          { resource: 'saleOffers',    action: 'view'   },
          { resource: 'saleOffers',    action: 'create' },
          { resource: 'saleDeals',     action: 'view'   },
          { resource: 'salePayments',  action: 'view'   },
          { resource: 'salePayments',  action: 'record' },
          { resource: 'saleReports',   action: 'view'   },
        ],
      },
      salesManager: {
        label: 'Sales Manager',
        description: 'Agent + manage listings, agents, approve offers, close deals, pay commissions',
        grants: [
          { resource: 'saleListings',    action: 'view'    },
          { resource: 'saleListings',    action: 'create'  },
          { resource: 'saleListings',    action: 'update'  },
          { resource: 'saleBuyers',      action: 'view'    },
          { resource: 'saleBuyers',      action: 'create'  },
          { resource: 'saleBuyers',      action: 'update'  },
          { resource: 'saleAgents',      action: 'view'    },
          { resource: 'saleAgents',      action: 'manage'  },
          { resource: 'saleOffers',      action: 'view'    },
          { resource: 'saleOffers',      action: 'create'  },
          { resource: 'saleOffers',      action: 'approve' },
          { resource: 'saleDeals',       action: 'view'    },
          { resource: 'saleDeals',       action: 'create'  },
          { resource: 'saleDeals',       action: 'close'   },
          { resource: 'salePayments',    action: 'view'    },
          { resource: 'salePayments',    action: 'record'  },
          { resource: 'saleCommissions', action: 'view'    },
          { resource: 'saleCommissions', action: 'pay'     },
          { resource: 'saleReports',     action: 'view'    },
          { resource: 'saleReports',     action: 'export'  },
        ],
      },
      admin: {
        label: 'Admin / Owner',
        description: 'Full access — all Property Sales permissions',
        grants: SALE,
      },
    },
  },

  hr: {
    label: 'HR Role',
    blockCls:    'border-rose-200 bg-rose-50',
    titleCls:    'text-rose-700',
    activeCls:   'border-rose-600 bg-rose-600 text-white',
    activeDescCls: 'text-rose-100',
    inactiveCls: 'border-rose-200 bg-white text-rose-800 hover:bg-rose-50',
    hintCls:     'text-rose-700/70',
    allPermissions: HR,
    roles: {
      hrOfficer: {
        label: 'HR Officer',
        description: 'Add/update employees, log leave, view payroll, complete appraisals',
        grants: [
          { resource: 'hrEmployees',  action: 'view'     },
          { resource: 'hrEmployees',  action: 'create'   },
          { resource: 'hrEmployees',  action: 'update'   },
          { resource: 'hrLeave',      action: 'view'     },
          { resource: 'hrLeave',      action: 'create'   },
          { resource: 'hrPayroll',    action: 'view'     },
          { resource: 'hrStatutory',  action: 'view'     },
          { resource: 'hrAppraisals', action: 'view'     },
          { resource: 'hrAppraisals', action: 'complete' },
          { resource: 'hrReports',    action: 'view'     },
          { resource: 'hrSetup',      action: 'view'     },
        ],
      },
      hrManager: {
        label: 'HR Manager',
        description: 'Officer + approve leave, run/approve payroll, process statutory, manage setup',
        grants: [
          { resource: 'hrEmployees',  action: 'view'      },
          { resource: 'hrEmployees',  action: 'create'    },
          { resource: 'hrEmployees',  action: 'update'    },
          { resource: 'hrEmployees',  action: 'terminate' },
          { resource: 'hrLeave',      action: 'view'      },
          { resource: 'hrLeave',      action: 'create'    },
          { resource: 'hrLeave',      action: 'approve'   },
          { resource: 'hrLeave',      action: 'manage'    },
          { resource: 'hrPayroll',    action: 'view'      },
          { resource: 'hrPayroll',    action: 'run'       },
          { resource: 'hrPayroll',    action: 'approve'   },
          { resource: 'hrStatutory',  action: 'view'      },
          { resource: 'hrStatutory',  action: 'process'   },
          { resource: 'hrAppraisals', action: 'view'      },
          { resource: 'hrAppraisals', action: 'create'    },
          { resource: 'hrAppraisals', action: 'complete'  },
          { resource: 'hrReports',    action: 'view'      },
          { resource: 'hrReports',    action: 'export'    },
          { resource: 'hrSetup',      action: 'view'      },
          { resource: 'hrSetup',      action: 'manage'    },
        ],
      },
      admin: {
        label: 'Admin / Owner',
        description: 'Full access — all HR permissions',
        grants: HR,
      },
    },
  },

  inventory: {
    label: 'Inventory / POS Role',
    blockCls:    'border-lime-200 bg-lime-50',
    titleCls:    'text-lime-700',
    activeCls:   'border-lime-600 bg-lime-600 text-white',
    activeDescCls: 'text-lime-100',
    inactiveCls: 'border-lime-200 bg-white text-lime-800 hover:bg-lime-50',
    hintCls:     'text-lime-700/70',
    allPermissions: INV,
    roles: {
      posCashier: {
        label: 'POS Cashier',
        description: 'Open POS terminal, sell, open/close sessions, view sales & reports',
        grants: [
          { resource: 'inv-products',  action: 'view'  },
          { resource: 'pos-terminal',  action: 'view'  },
          { resource: 'pos-terminal',  action: 'sell'  },
          { resource: 'pos-sessions',  action: 'view'  },
          { resource: 'pos-sessions',  action: 'open'  },
          { resource: 'pos-sessions',  action: 'close' },
          { resource: 'pos-sales',     action: 'view'  },
          { resource: 'pos-reports',   action: 'view'  },
        ],
      },
      stockController: {
        label: 'Stock Controller',
        description: 'View & adjust stock, receive transfers, view reports',
        grants: [
          { resource: 'inv-dashboard',  action: 'view'    },
          { resource: 'inv-products',   action: 'view'    },
          { resource: 'inv-categories', action: 'view'    },
          { resource: 'inv-suppliers',  action: 'view'    },
          { resource: 'inv-transfers',  action: 'view'    },
          { resource: 'inv-transfers',  action: 'receive' },
          { resource: 'inv-stock',      action: 'view'    },
          { resource: 'inv-stock',      action: 'adjust'  },
          { resource: 'inv-tills',      action: 'view'    },
          { resource: 'inv-reports',    action: 'view'    },
        ],
      },
      inventoryManager: {
        label: 'Inventory Manager',
        description: 'Controller + manage products, POs, transfers, tills & reports',
        grants: [
          { resource: 'inv-dashboard',       action: 'view'     },
          { resource: 'inv-locations',       action: 'view'     },
          { resource: 'inv-locations',       action: 'manage'   },
          { resource: 'inv-categories',      action: 'view'     },
          { resource: 'inv-categories',      action: 'manage'   },
          { resource: 'inv-products',        action: 'view'     },
          { resource: 'inv-products',        action: 'create'   },
          { resource: 'inv-products',        action: 'update'   },
          { resource: 'inv-suppliers',       action: 'view'     },
          { resource: 'inv-suppliers',       action: 'manage'   },
          { resource: 'inv-purchase-orders', action: 'view'     },
          { resource: 'inv-purchase-orders', action: 'create'   },
          { resource: 'inv-purchase-orders', action: 'receive'  },
          { resource: 'inv-transfers',       action: 'view'     },
          { resource: 'inv-transfers',       action: 'create'   },
          { resource: 'inv-transfers',       action: 'dispatch' },
          { resource: 'inv-transfers',       action: 'receive'  },
          { resource: 'inv-stock',           action: 'view'     },
          { resource: 'inv-stock',           action: 'adjust'   },
          { resource: 'inv-stock',           action: 'writeoff' },
          { resource: 'inv-tills',           action: 'view'     },
          { resource: 'inv-tills',           action: 'manage'   },
          { resource: 'inv-reports',         action: 'view'     },
          { resource: 'inv-reports',         action: 'export'   },
          { resource: 'pos-terminal',        action: 'view'     },
          { resource: 'pos-terminal',        action: 'void'     },
          { resource: 'pos-sessions',        action: 'view'     },
          { resource: 'pos-sales',           action: 'view'     },
          { resource: 'pos-sales',           action: 'export'   },
          { resource: 'pos-reports',         action: 'view'     },
        ],
      },
      admin: {
        label: 'Admin / Owner',
        description: 'Full access — all Inventory & POS permissions',
        grants: INV,
      },
    },
  },
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Clears all permissions for a module then grants the chosen role's set.
 */
export const applyModuleRole = (currentPermissions, moduleKey, roleKey) => {
  const preset = MODULE_ROLE_PRESETS[moduleKey];
  if (!preset) return currentPermissions;
  const role = preset.roles[roleKey];
  if (!role) return currentPermissions;
  const cleared = setPermissionGroupValue(currentPermissions, preset.allPermissions, false);
  return setPermissionGroupValue(cleared, role.grants, true);
};

/**
 * Returns the roleKey that exactly matches the current permissions for this module,
 * or 'custom' if none matches.
 */
export const detectModuleRole = (permissions, moduleKey) => {
  const preset = MODULE_ROLE_PRESETS[moduleKey];
  if (!preset) return 'custom';
  for (const [key, role] of Object.entries(preset.roles)) {
    const allGranted = role.grants.every((p) => permissions?.[p.resource]?.[p.action] === true);
    const noExtra    = preset.allPermissions
      .filter((p) => !role.grants.some((g) => g.resource === p.resource && g.action === p.action))
      .every((p) => !permissions?.[p.resource]?.[p.action]);
    if (allGranted && noExtra) return key;
  }
  return 'custom';
};
