import React, { useCallback, useEffect, useMemo, useState } from "react";
import AppSelect from "../../components/common/AppSelect";
import { useLocation } from "react-router-dom";
import useDebounce from "../../hooks/useDebounce";
import {
  FaBookOpen,
  FaCheck,
  FaEdit,
  FaFilter,
  FaPlus,
  FaRedoAlt,
  FaSearch,
  FaTimes,
  FaTrash,
  FaUndo,
} from "react-icons/fa";
import { useDispatch, useSelector } from "react-redux";
import { toast } from "react-toastify";
import DashboardLayout from "../../components/Layout/DashboardLayout";
import { isSelfManagingLandlordCompany } from "../../utils/companyModules";
import { selectCurrentCompany, selectCurrentUser, selectAllProperties } from "../../redux/selectors";
import { getProperties } from "../../redux/propertyRedux";
import {
  createJournalEntry,
  deleteJournalEntry,
  getChartOfAccounts,
  getJournalEntries,
  postJournalEntry,
  reverseJournalEntry,
  updateJournalEntry,
} from "../../redux/apiCalls";
import { hasCompanyPermission } from "../../utils/permissions";
import useScopedSessionDraft, { buildScopedDraftKey } from "../../hooks/useScopedSessionDraft";
import { useConfirm } from "../../context/ConfirmContext";

const JOURNAL_TYPES = [
  {
    value: "general_manual_journal",
    label: "General Journal",
    description: "Standard double-entry journal. Select any two posting accounts from the Chart of Accounts. Property context is derived automatically from property-specific accounts (e.g. 2110-PARK).",
  },
  {
    value: "internal_account_transfer",
    label: "Internal Ledger Transfer",
    description: "Moves value between two ledger accounts within the same company. Never appears on any owner statement.",
  },
  {
    value: "landlord_credit_adjustment",
    label: "Owner / Creditor Credit",
    description: "Credits the Owner Remittance Payable account to raise an owner-facing addition. Select the property-specific remittance account (e.g. 2110-PARK) as the credit leg.",
  },
  {
    value: "landlord_debit_adjustment",
    label: "Owner / Creditor Debit",
    description: "Debits the Owner Remittance Payable account to post an owner-facing deduction. Select the property-specific remittance account (e.g. 2110-PARK) as the debit leg.",
  },
  {
    value: "property_expense_accrual",
    label: "Expense Accrual / Owner Deduction",
    description: "Accrues a property expense by debiting Owner Remittance Payable and crediting the accrual or offset account.",
  },
  {
    value: "company_journal",
    label: "Company Journal (Internal)",
    description: "Internal company-level journal with no property context. Use for head-office allocations, reclassifications, or company-wide adjustments. Never appears on any owner statement.",
  },
  {
    value: "payroll_posting",
    label: "Payroll Posting (HR)",
    description: "Auto-generated by the HR module when payroll is processed. Read-only in this view.",
  },
  {
    value: "statutory_payment",
    label: "Statutory Payment (HR)",
    description: "Auto-generated by the HR module for statutory remittances (PAYE, NSSF, NHIF). Read-only in this view.",
  },
];

const STATUS_STYLES = {
  draft: "bg-slate-100 text-slate-700 border-slate-200",
  posted: "bg-green-100 text-green-700 border-green-200",
  reversed: "bg-amber-100 text-amber-700 border-amber-200",
};

const isLandlordPayableAccountRecord = (account = {}) => {
  const code = String(account?.code || account?.accountCode || "").trim().toUpperCase();
  const name = String(account?.name || account?.accountName || account?.title || "").trim().toLowerCase();
  return (
    code === "2110" ||
    /landlord remittance payable|landlord payable|owner payable|owner remittance payable/.test(name)
  );
};

const DEFAULT_PAGE_SIZE = 50;

const buildInitialForm = () => ({
  date: new Date().toISOString().split("T")[0],
  journalType: "general_manual_journal",
  debitAccount: "",
  creditAccount: "",
  amount: "",
  reference: "",
  narration: "",
  includeInLandlordStatement: false,
});

const JournalEntries = () => {
  const confirm = useConfirm();
  const dispatch = useDispatch();
  const location = useLocation();
  const isAccountsWorkspace = location.pathname.startsWith("/accounts/");
  const currentCompany = useSelector(selectCurrentCompany);
  const currentUser = useSelector(selectCurrentUser);
  const properties = useSelector(selectAllProperties);
  const canCreateJournal = hasCompanyPermission(currentUser || {}, currentCompany, "journals", "create", "accounts");
  const canUpdateJournal = hasCompanyPermission(currentUser || {}, currentCompany, "journals", "update", "accounts");
  const canPostJournal = hasCompanyPermission(currentUser || {}, currentCompany, "journals", "process", "accounts");
  const canReverseJournal = hasCompanyPermission(currentUser || {}, currentCompany, "journals", "reverse", "accounts");
  const canDeleteJournal = hasCompanyPermission(currentUser || {}, currentCompany, "journals", "delete", "accounts");
  const isLandlordWorkspace = useMemo(
    () => isSelfManagingLandlordCompany(currentCompany || currentUser?.company || null),
    [currentCompany, currentUser?.company]
  );

  const journalDraftKey = buildScopedDraftKey({
    page: "journal-entries",
    companyId: currentCompany?._id,
    userId: currentUser?._id || currentUser?.id || currentUser?.email,
  });
  const [journalDraft, setJournalDraft, clearJournalDraft] = useScopedSessionDraft(journalDraftKey, {
    showCreateModal: false,
    editingJournalId: "",
    filters: {
      search: "",
      status: "all",
      journalType: "all",
      propertyId: "all",
    },
    form: buildInitialForm(),
  });

  const [journals, setJournals] = useState([]);
  const [accounts, setAccounts] = useState([]);
  const [loading, setLoading] = useState(false);
  const [rowActionKey, setRowActionKey] = useState("");
  const showCreateModal = Boolean(journalDraft.showCreateModal);
  const setShowCreateModal = (value) => setJournalDraft((prev) => ({ ...prev, showCreateModal: typeof value === "function" ? value(Boolean(prev.showCreateModal)) : Boolean(value) }));
  const editingJournalId = journalDraft.editingJournalId || "";
  const setEditingJournalId = (value) => setJournalDraft((prev) => ({ ...prev, editingJournalId: typeof value === "function" ? value(prev.editingJournalId || "") : value }));
  const [saving, setSaving] = useState(false);

  const filters = journalDraft.filters || { search: "", status: "all", journalType: "all", propertyId: "all" };
  const debouncedSearch = useDebounce(filters.search, 400);
  const setFilters = (value) => setJournalDraft((prev) => ({ ...prev, filters: typeof value === "function" ? value(prev.filters || filters) : value }));

  const form = journalDraft.form || buildInitialForm();
  const setForm = (value) => setJournalDraft((prev) => ({ ...prev, form: typeof value === "function" ? value(prev.form || buildInitialForm()) : value }));
  const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE);
  const [currentPage, setCurrentPage] = useState(1);
  const [serverTotal, setServerTotal] = useState(0);
  const [serverPages, setServerPages] = useState(1);

  useEffect(() => {
    if (currentCompany?._id) dispatch(getProperties({ business: currentCompany._id }));
  }, [dispatch, currentCompany?._id]);

  const propertyOptions = useMemo(
    () => properties.map((p) => ({ value: p._id, label: p.propertyName || p.name || "Property" })),
    [properties]
  );

  useEffect(() => {
    const loadAccounts = async () => {
      if (!currentCompany?._id) return;
      try {
        const rows = await getChartOfAccounts({ business: currentCompany._id });
        setAccounts(
          Array.isArray(rows)
            ? rows.filter((row) => row?.isPosting !== false && row?.isHeader !== true)
            : []
        );
      } catch (error) {
        toast.error(
          error?.response?.data?.error ||
            error?.response?.data?.message ||
            "Failed to load chart of accounts"
        );
      }
    };

    loadAccounts();
  }, [currentCompany?._id]);

  const loadJournals = useCallback(async () => {
    if (!currentCompany?._id) return;
    setLoading(true);
    try {
      const { data: rows, total, pages } = await getJournalEntries({
        business: currentCompany._id,
        company: currentCompany._id,
        ...(isAccountsWorkspace ? {} : { excludeSourceModules: "hr,carwash" }),
        ...filters,
        search: debouncedSearch,
        page: currentPage,
        limit: pageSize,
      });
      setJournals(Array.isArray(rows) ? rows : []);
      setServerTotal(total ?? 0);
      setServerPages(pages ?? 1);
    } catch (error) {
      toast.error(error?.response?.data?.message || "Failed to load journal entries");
    } finally {
      setLoading(false);
    }
  }, [currentCompany?._id, isAccountsWorkspace, debouncedSearch, filters.status, filters.journalType, filters.propertyId, currentPage, pageSize]);

  useEffect(() => { loadJournals(); }, [loadJournals]);

  const totals = useMemo(() => {
    return journals.reduce(
      (acc, item) => {
        const amount = Number(item.amount || 0);
        acc.total += amount;
        if (item.status === "draft") acc.draft += amount;
        if (item.status === "posted") acc.posted += amount;
        if (item.status === "reversed") acc.reversed += amount;
        return acc;
      },
      { total: 0, draft: 0, posted: 0, reversed: 0 }
    );
  }, [journals]);


  const totalPages = Math.max(1, serverPages);
  const safeCurrentPage = Math.min(currentPage, totalPages);
  const currentPageRows = journals;

  useEffect(() => {
    setCurrentPage(1);
  }, [debouncedSearch, filters.status, filters.journalType, filters.propertyId, pageSize]);

  const accountOptions = useMemo(
    () =>
      accounts.map((a) => ({
        value: a._id,
        label: `${a.code} – ${a.name}`,
        description: [
          a.type ? a.type.charAt(0).toUpperCase() + a.type.slice(1) : "",
          a.subGroup || a.group || "",
        ]
          .filter(Boolean)
          .join(" · "),
        isControl: Boolean(a.isControl),
      })),
    [accounts]
  );

  const selectedDebitAccountRecord = useMemo(
    () => accounts.find((account) => String(account?._id || "") === String(form.debitAccount || "")) || null,
    [accounts, form.debitAccount]
  );

  const selectedCreditAccountRecord = useMemo(
    () => accounts.find((account) => String(account?._id || "") === String(form.creditAccount || "")) || null,
    [accounts, form.creditAccount]
  );

  const getJournalTypePresentation = (journalType) =>
    JOURNAL_TYPES.find((type) => type.value === journalType) || JOURNAL_TYPES[0];

  const activeJournalTypePresentation = useMemo(
    () => getJournalTypePresentation(form.journalType),
    [form.journalType]
  );

  const isCompanyJournal = form.journalType === "company_journal";
  const isInternalTransferJournal = form.journalType === "internal_account_transfer";
  const isForcedLandlordStatementJournal =
    !isCompanyJournal &&
    (form.journalType === "landlord_credit_adjustment" ||
      form.journalType === "landlord_debit_adjustment" ||
      form.journalType === "property_expense_accrual");
  const debitTouchesLandlordPayable = !isCompanyJournal && isLandlordPayableAccountRecord(selectedDebitAccountRecord);
  const creditTouchesLandlordPayable = !isCompanyJournal && isLandlordPayableAccountRecord(selectedCreditAccountRecord);
  const statementVisibilityLocked = isCompanyJournal || isInternalTransferJournal || isForcedLandlordStatementJournal;
  const controlAccountWarning = useMemo(() => {
    const warnings = [];
    if (selectedDebitAccountRecord?.isControl) warnings.push(`Dr: "${selectedDebitAccountRecord.name}" is a control account managed by a module. Post through the module instead, or select a different account.`);
    if (selectedCreditAccountRecord?.isControl) warnings.push(`Cr: "${selectedCreditAccountRecord.name}" is a control account managed by a module. Post through the module instead, or select a different account.`);
    return warnings;
  }, [selectedDebitAccountRecord, selectedCreditAccountRecord]);

  const journalStructureHint = useMemo(() => {
    if (form.journalType === "company_journal") {
      return "Company journals are internal-only. No property or owner context is attached. These entries never appear on any owner statement.";
    }
    if (form.journalType === "landlord_credit_adjustment") {
      return "Select the property-specific Owner Remittance Payable (e.g. 2110-PARK) as the credit leg and a balancing account as the debit. This creates one clean owner statement addition.";
    }
    if (form.journalType === "landlord_debit_adjustment") {
      return "Select the property-specific Owner Remittance Payable (e.g. 2110-PARK) as the debit leg and a balancing account as the credit. This creates one clean owner statement deduction.";
    }
    if (form.journalType === "property_expense_accrual") {
      return "Debit the Owner Remittance Payable account (e.g. 2110-PARK) and credit the accrual or offset account. The property context is derived automatically from the account.";
    }
    if (form.journalType === "internal_account_transfer") {
      return "Internal transfers stay inside the same company only and must not use Owner Remittance Payable or appear on any owner statement.";
    }
    if (form.includeInLandlordStatement) {
      return "Statement-visible general journals must touch Owner Remittance Payable on exactly one side. Debit = deduction. Credit = addition.";
    }
    return "The account selection carries all context — select property-specific accounts (e.g. 2110-PARK) to automatically link to a property and owner.";
  }, [form.includeInLandlordStatement, form.journalType]);

  const applyJournalTypeDefaults = (journalType) => {
    const landlordStatementJournal =
      journalType === "landlord_credit_adjustment" ||
      journalType === "landlord_debit_adjustment" ||
      journalType === "property_expense_accrual";

    setForm((prev) => ({
      ...prev,
      journalType,
      includeInLandlordStatement:
        journalType === "company_journal" || journalType === "internal_account_transfer"
          ? false
          : landlordStatementJournal,
    }));
  };

  const resetForm = () => {
    setEditingJournalId("");
    setForm(buildInitialForm());
    clearJournalDraft();
  };

  const openCreateModal = () => {
    if (!canCreateJournal) {
      toast.warning("You do not have permission to create journals");
      return;
    }
    setEditingJournalId("");
    setForm(buildInitialForm());
    setShowCreateModal(true);
  };

  const openEditModal = (journal) => {
    if (!canUpdateJournal) {
      toast.warning("You do not have permission to edit journals");
      return;
    }
    if (journal?.status !== "draft") {
      toast.info("Only draft journals can be edited directly. Reverse posted journals and recreate them if needed.");
      return;
    }

    setEditingJournalId(String(journal._id || ""));
    setForm({
      date: journal?.date ? new Date(journal.date).toISOString().split("T")[0] : new Date().toISOString().split("T")[0],
      journalType: journal?.journalType || "general_manual_journal",
      debitAccount: journal?.debitAccount?._id || journal?.debitAccount || "",
      creditAccount: journal?.creditAccount?._id || journal?.creditAccount || "",
      amount: journal?.amount || "",
      reference: journal?.reference || "",
      narration: journal?.narration || "",
      includeInLandlordStatement: Boolean(journal?.includeInLandlordStatement),
    });
    setShowCreateModal(true);
  };

  const closeCreateModal = () => {
    setShowCreateModal(false);
    resetForm();
  };


  const handleSaveJournal = async () => {
    if (!(editingJournalId ? canUpdateJournal : canCreateJournal)) {
      toast.warning(editingJournalId ? "You do not have permission to update journals" : "You do not have permission to create journals");
      return;
    }
    if (!currentCompany?._id) {
      toast.warning("Please select a company first");
      return;
    }

    if (!form.debitAccount) {
      toast.warning("Debit account is required");
      return;
    }

    if (!form.creditAccount) {
      toast.warning("Credit account is required");
      return;
    }

    if (form.debitAccount === form.creditAccount) {
      toast.warning("Debit and credit accounts must be different");
      return;
    }

    if (!form.amount || Number(form.amount) <= 0) {
      toast.warning("Amount must be greater than zero");
      return;
    }

    if (isInternalTransferJournal && (debitTouchesLandlordPayable || creditTouchesLandlordPayable)) {
      toast.warning("Internal ledger transfers cannot use Landlord Remittance Payable.");
      return;
    }

    if (form.journalType === "landlord_credit_adjustment" && (!creditTouchesLandlordPayable || debitTouchesLandlordPayable)) {
      toast.warning("Landlord Credit Adjustment must credit Landlord Remittance Payable.");
      return;
    }

    if (["landlord_debit_adjustment", "property_expense_accrual"].includes(form.journalType) && (!debitTouchesLandlordPayable || creditTouchesLandlordPayable)) {
      toast.warning(
        form.journalType === "property_expense_accrual"
          ? "Property Expense / Landlord Deduction must debit Landlord Remittance Payable."
          : "Landlord Debit Adjustment must debit Landlord Remittance Payable."
      );
      return;
    }

    if (
      form.journalType === "general_manual_journal" &&
      form.includeInLandlordStatement &&
      debitTouchesLandlordPayable === creditTouchesLandlordPayable
    ) {
      toast.warning("Statement-visible general journals must touch Landlord Remittance Payable on exactly one side.");
      return;
    }

    const payload = {
      business: currentCompany._id,
      company: currentCompany._id,
      date: form.date,
      journalType: form.journalType,
      debitAccount: form.debitAccount,
      creditAccount: form.creditAccount,
      amount: Number(form.amount),
      reference: form.reference,
      narration: form.narration,
      includeInLandlordStatement: isCompanyJournal || isInternalTransferJournal
        ? false
        : isForcedLandlordStatementJournal
        ? true
        : Boolean(form.includeInLandlordStatement),
      sourceModule: isAccountsWorkspace ? "accounts" : "propertyManagement",
    };

    setSaving(true);
    try {
      const saved = editingJournalId
        ? await updateJournalEntry(editingJournalId, payload)
        : await createJournalEntry(payload);

      setJournals((prev) =>
        editingJournalId
          ? prev.map((row) => (row._id === editingJournalId ? saved : row))
          : [saved, ...prev]
      );
      toast.success(
        editingJournalId
          ? `Journal ${saved?.journalNo || ""} updated`
          : `Journal ${saved?.journalNo || ""} created`
      );
      closeCreateModal();
    } catch (error) {
      toast.error(
        error?.response?.data?.message ||
          (editingJournalId ? "Failed to update journal" : "Failed to create journal")
      );
    } finally {
      setSaving(false);
    }
  };

  const handlePostJournal = async (journal) => {
    if (!canPostJournal) {
      toast.warning("You do not have permission to post journals");
      return;
    }
    setRowActionKey(`${journal._id}:post`);
    try {
      const updated = await postJournalEntry(journal._id, {
        business: currentCompany?._id,
        company: currentCompany?._id,
      });
      setJournals((prev) => prev.map((row) => (row._id === journal._id ? updated : row)));
      toast.success(`Journal ${updated?.journalNo || ""} posted`);
    } catch (error) {
      toast.error(error?.response?.data?.message || "Failed to post journal");
    } finally {
      setRowActionKey("");
    }
  };

  const handleReverseJournal = async (journal) => {
    if (!canReverseJournal) {
      toast.warning("You do not have permission to reverse journals");
      return;
    }
    const ok = await confirm({ title: "Reverse Journal", message: `Reverse journal ${journal.journalNo}? A reversing entry will be created.`, confirmText: "Reverse" });
    if (!ok) return;

    setRowActionKey(`${journal._id}:reverse`);
    try {
      const updated = await reverseJournalEntry(journal._id, {
        business: currentCompany?._id,
        company: currentCompany?._id,
        reason: `Journal ${journal.journalNo} reversed`,
      });
      setJournals((prev) => prev.map((row) => (row._id === journal._id ? updated : row)));
      toast.success(`Journal ${updated?.journalNo || ""} reversed`);
    } catch (error) {
      toast.error(error?.response?.data?.message || "Failed to reverse journal");
    } finally {
      setRowActionKey("");
    }
  };

  const handleDeleteJournal = async (journal) => {
    if (!canDeleteJournal) {
      toast.warning("You do not have permission to delete journals");
      return;
    }
    const ok = await confirm({ title: "Delete Journal", message: `Delete draft journal ${journal.journalNo}?`, confirmText: "Delete", isDangerous: true });
    if (!ok) return;

    setRowActionKey(`${journal._id}:delete`);
    try {
      await deleteJournalEntry(journal._id, {
        business: currentCompany?._id,
        company: currentCompany?._id,
      });
      setJournals((prev) => prev.filter((row) => row._id !== journal._id));
      toast.success("Journal deleted");
    } catch (error) {
      toast.error(error?.response?.data?.message || "Failed to delete journal");
    } finally {
      setRowActionKey("");
    }
  };

  return (
    <DashboardLayout lockContentScroll>
      <div className="flex h-full min-h-0 flex-col overflow-hidden bg-slate-50 p-2">
        <div className="mx-auto flex w-full max-w-full min-h-0 flex-1 flex-col gap-2">

          {/* KPI Strip */}
          <div className="grid flex-shrink-0 grid-cols-2 gap-2 md:grid-cols-4">
            {[
              { label: "Total Entries", value: journals.length, sub: `KES ${totals.total.toLocaleString()}`, cls: "bg-slate-900 text-white" },
              { label: "Draft", value: journals.filter((j) => j.status === "draft").length, sub: `KES ${totals.draft.toLocaleString()}`, cls: "bg-amber-50 text-amber-800 border border-amber-200" },
              { label: "Posted", value: journals.filter((j) => j.status === "posted").length, sub: `KES ${totals.posted.toLocaleString()}`, cls: "bg-emerald-50 text-emerald-800 border border-emerald-200" },
              { label: "Reversed", value: journals.filter((j) => j.status === "reversed").length, sub: `KES ${totals.reversed.toLocaleString()}`, cls: "bg-rose-50 text-rose-800 border border-rose-200" },
            ].map((card) => (
              <div key={card.label} className={`rounded-lg px-3 py-2 shadow-sm ${card.cls}`}>
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold uppercase tracking-wider opacity-75">{card.label}</span>
                  <span className="text-sm font-black">{card.value}</span>
                </div>
                <p className="truncate text-[9px] font-semibold opacity-50">{card.sub}</p>
              </div>
            ))}
          </div>

          <div className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
            <div className="flex-none sticky top-0 z-20 border-b border-slate-200 bg-white shadow-sm">
              <div className="flex items-center gap-1.5 overflow-x-auto px-2 py-1.5">
                <div className="relative shrink-0">
                  <FaSearch className="absolute left-2 top-1/2 -translate-y-1/2 text-[10px] text-slate-400" />
                  <input
                    value={filters.search}
                    onChange={(e) => setFilters((prev) => ({ ...prev, search: e.target.value }))}
                    placeholder="Journal no, reference, narration"
                    className="h-7 w-44 rounded border border-slate-200 bg-white pl-6 pr-2 text-xs focus:outline-none focus:ring-1 focus:ring-[#0B3B2E]"
                  />
                </div>
                <select
                  value={filters.status}
                  onChange={(e) => setFilters((prev) => ({ ...prev, status: e.target.value }))}
                  className="h-7 shrink-0 rounded border border-slate-200 bg-white px-2 text-xs appearance-none focus:outline-none focus:ring-1 focus:ring-[#0B3B2E]"
                >
                  <option value="all">All Statuses</option>
                  <option value="draft">Draft</option>
                  <option value="posted">Posted</option>
                  <option value="reversed">Reversed</option>
                </select>
                <select
                  value={filters.journalType}
                  onChange={(e) => setFilters((prev) => ({ ...prev, journalType: e.target.value }))}
                  className="h-7 shrink-0 rounded border border-slate-200 bg-white px-2 text-xs appearance-none focus:outline-none focus:ring-1 focus:ring-[#0B3B2E]"
                >
                  <option value="all">All Journal Types</option>
                  {JOURNAL_TYPES.map((type) => (
                    <option key={type.value} value={type.value}>
                      {getJournalTypePresentation(type.value)?.label || type.label}
                    </option>
                  ))}
                </select>
                <select
                  value={filters.propertyId}
                  onChange={(e) => setFilters((prev) => ({ ...prev, propertyId: e.target.value }))}
                  className="h-7 shrink-0 rounded border border-slate-200 bg-white px-2 text-xs appearance-none focus:outline-none focus:ring-1 focus:ring-[#0B3B2E]"
                >
                  <option value="all">All Properties</option>
                  {propertyOptions.map((item) => (
                    <option key={item.value} value={item.value}>
                      {item.label}
                    </option>
                  ))}
                </select>
                <button
                  onClick={() => setFilters({ search: "", status: "all", journalType: "all", propertyId: "all" })}
                  className="h-7 shrink-0 flex items-center gap-1 rounded border border-slate-200 bg-white px-2.5 text-xs font-semibold text-slate-700 hover:bg-slate-50"
                >
                  <FaFilter size={9} /> Reset
                </button>
                <button onClick={loadJournals} className="h-7 shrink-0 flex items-center gap-1 rounded border border-slate-200 bg-white px-2.5 text-xs font-semibold text-slate-700 hover:bg-slate-50"><FaRedoAlt size={9} /></button>
                <button onClick={openCreateModal} className="h-7 shrink-0 flex items-center gap-1 rounded bg-[#0B3B2E] px-2.5 text-xs font-semibold text-white hover:bg-[#0A3127]"><FaPlus size={9} /> New Journal</button>
              </div>
            </div>

            <div className="flex-1 min-h-0 overflow-auto">
              <table className="w-full min-w-[1440px] text-[11px] border-collapse">
                <thead className="sticky top-0 z-10 shadow-sm">
                  <tr className="bg-[#0B3B2E] text-white">
                    <th className="px-3 py-1 text-left font-black border-r border-white/10">Journal</th>
                    <th className="px-3 py-1 text-left font-black border-r border-white/10">Date</th>
                    <th className="px-3 py-1 text-left font-black border-r border-white/10">Type</th>
                    <th className="px-3 py-1 text-left font-black border-r border-white/10">Property</th>
                    <th className="px-3 py-1 text-left font-black border-r border-white/10">{isLandlordWorkspace ? "Owner" : "Landlord"}</th>
                    <th className="px-3 py-1 text-left font-black border-r border-white/10">Debit</th>
                    <th className="px-3 py-1 text-left font-black border-r border-white/10">Credit</th>
                    <th className="px-3 py-1 text-right font-black border-r border-white/10">Amount</th>
                    <th className="px-3 py-1 text-left font-black border-r border-white/10">Status</th>
                    <th className="px-3 py-1 text-right font-black">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {loading ? (
                    <tr>
                      <td colSpan={10} className="px-4 py-10 text-center text-slate-500">Loading journals...</td>
                    </tr>
                  ) : journals.length === 0 ? (
                    <tr>
                      <td colSpan={10} className="px-4 py-10 text-center text-slate-500">No journals found.</td>
                    </tr>
                  ) : (
                    currentPageRows.map((journal, index) => {
                      const busyPost = rowActionKey === `${journal._id}:post`;
                      const busyReverse = rowActionKey === `${journal._id}:reverse`;
                      const busyDelete = rowActionKey === `${journal._id}:delete`;

                      return (
                        <tr
                          key={journal._id}
                          className={`border-b border-gray-100 ${index % 2 === 0 ? "bg-white" : "bg-slate-50/60"} hover:bg-blue-50/40`}
                        >
                          <td className="px-3 py-1 border-r border-gray-100">
                            <div className="font-black text-slate-900">{journal.journalNo}</div>
                            <div className="text-[10px] text-slate-500">{journal.reference || journal.narration || "No reference"}</div>
                          </td>
                          <td className="px-3 py-1 border-r border-gray-100 text-slate-700">{journal.date ? new Date(journal.date).toLocaleDateString() : "-"}</td>
                          <td className="px-3 py-1 border-r border-gray-100 text-slate-700">{getJournalTypePresentation(journal.journalType)?.label || journal.journalType}</td>
                          <td className="px-3 py-1 border-r border-gray-100 text-slate-700">{journal.property?.propertyName || journal.property?.name || "N/A"}</td>
                          <td className="px-3 py-1 border-r border-gray-100 text-slate-700">{journal.landlord?.landlordName || journal.landlord?.name || "-"}</td>
                          <td className="px-3 py-1 border-r border-gray-100 text-slate-700">{journal.debitAccount?.code} - {journal.debitAccount?.name}</td>
                          <td className="px-3 py-1 border-r border-gray-100 text-slate-700">{journal.creditAccount?.code} - {journal.creditAccount?.name}</td>
                          <td className="px-3 py-1 border-r border-gray-100 text-right font-black text-slate-900">KES {Number(journal.amount || 0).toLocaleString()}</td>
                          <td className="px-3 py-1 border-r border-gray-100">
                            <span className={`inline-flex rounded-full border px-2 py-0.5 text-[10px] font-black ${STATUS_STYLES[journal.status] || STATUS_STYLES.draft}`}>
                              {journal.status}
                            </span>
                          </td>
                          <td className="px-3 py-1 text-right">
                            <div className="inline-flex flex-wrap justify-end gap-2">
                              {journal.status === "draft" && (
                                <>
                                  <button
                                    onClick={() => openEditModal(journal)}
                                    disabled={!canUpdateJournal || !!rowActionKey}
                                    className="inline-flex items-center gap-1 rounded-lg border border-blue-300 bg-blue-50 px-3 py-2 text-xs font-black text-blue-700 disabled:opacity-60"
                                  >
                                    <FaEdit /> Edit
                                  </button>
                                  <button
                                    onClick={() => handlePostJournal(journal)}
                                    disabled={!canPostJournal || !!rowActionKey}
                                    className="inline-flex items-center gap-1 rounded-lg border border-green-300 bg-green-50 px-3 py-2 text-xs font-black text-green-700 disabled:opacity-60"
                                  >
                                    <FaCheck /> {busyPost ? "Posting..." : "Post"}
                                  </button>
                                  <button
                                    onClick={() => handleDeleteJournal(journal)}
                                    disabled={!canDeleteJournal || !!rowActionKey}
                                    className="inline-flex items-center gap-1 rounded-lg border border-rose-300 bg-rose-50 px-3 py-2 text-xs font-black text-rose-700 disabled:opacity-60"
                                  >
                                    <FaTrash /> {busyDelete ? "Deleting..." : "Delete"}
                                  </button>
                                </>
                              )}
                              {journal.status === "posted" && (
                                <button
                                  onClick={() => handleReverseJournal(journal)}
                                  disabled={!canReverseJournal || !!rowActionKey}
                                  className="inline-flex items-center gap-1 rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-xs font-black text-amber-700 disabled:opacity-60"
                                >
                                  <FaUndo /> {busyReverse ? "Reversing..." : "Reverse"}
                                </button>
                              )}
                            </div>
                          </td>
                        </tr>
                      );
                    })
                  )}
                </tbody>
              </table>
            </div>
            <div className="flex flex-shrink-0 flex-wrap items-center justify-between gap-3 border-t border-slate-200 bg-white px-3 py-2 text-xs text-slate-600">
              <div className="font-semibold">Showing <span className="font-bold text-slate-900">{journals.length === 0 ? 0 : (safeCurrentPage - 1) * pageSize + 1}</span> to <span className="font-bold text-slate-900">{Math.min(safeCurrentPage * pageSize, serverTotal)}</span> of <span className="font-bold text-slate-900">{serverTotal}</span> journal(s)</div>
              <div className="flex items-center gap-3"><div className="flex items-center gap-1.5"><span className="font-semibold text-slate-500">Per page:</span><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setCurrentPage(1); }} className="h-7 rounded border border-slate-200 bg-slate-50 px-2 text-xs font-bold text-slate-700 focus:border-[#0B3B2E] focus:outline-none transition">{[25, 50, 100, 200].map((n) => <option key={n} value={n}>{n}</option>)}</select></div><button onClick={() => setCurrentPage((prev) => Math.max(1, prev - 1))} disabled={safeCurrentPage === 1} className="rounded-lg border border-slate-300 px-3 py-1 font-semibold transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50">Previous</button><span className="font-semibold text-slate-700">Page {safeCurrentPage} of {totalPages}</span><button onClick={() => setCurrentPage((prev) => Math.min(totalPages, prev + 1))} disabled={safeCurrentPage === totalPages} className="rounded-lg border border-slate-300 px-3 py-1 font-semibold transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50">Next</button></div>
            </div>
          </div>
        </div>
      </div>

      {showCreateModal && (
        <div className="fixed inset-0 z-[120] flex items-start justify-center overflow-y-auto bg-slate-900/45 p-4 sm:items-center sm:p-6">
          <div className="flex w-full max-w-5xl max-h-[calc(100vh-2rem)] flex-col overflow-y-auto overscroll-contain rounded-3xl border border-slate-200 bg-white shadow-2xl sm:max-h-[calc(100vh-3rem)]">
            <div className="sticky top-0 z-20 flex shrink-0 items-center justify-between bg-[#0B3B2E] px-6 py-4 text-white">
              <div>
                <p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-100">Financial Accounts</p>
                <h3 className="text-xl font-black">{editingJournalId ? "Edit Draft Journal" : "Create Journal Entry"}</h3>
                <p className="mt-1 text-xs text-emerald-50">
                  {editingJournalId
                    ? "Only draft journals can be edited directly. Posted journals must be reversed to preserve audit integrity."
                    : "Draft first, then review and post from the journal list."}
                </p>
              </div>
              <button
                onClick={closeCreateModal}
                className="rounded-full border border-white/30 p-2 hover:bg-white/10"
              >
                <FaTimes />
              </button>
            </div>

            <div className="grid gap-4 p-6 lg:grid-cols-[1.15fr,0.85fr]">
              <div className="space-y-4">
                <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
                  <p className="text-xs font-black uppercase tracking-[0.18em] text-slate-500">Journal type</p>
                  <div className="mt-2">
                    <AppSelect
                      value={form.journalType}
                      onChange={(val) => applyJournalTypeDefaults(val ?? "general_manual_journal")}
                      options={JOURNAL_TYPES.map((t) => ({
                        value: t.value,
                        label: getJournalTypePresentation(t.value)?.label || t.label,
                        description: t.description,
                      }))}
                      size="sm"
                    />
                  </div>
                  <p className="mt-3 text-xs leading-6 text-slate-600">{activeJournalTypePresentation.description}</p>
                </div>

                <div className="grid gap-4 md:grid-cols-2">
                  <label className="block">
                    <span className="text-xs font-bold text-slate-700">Journal Date</span>
                    <input
                      type="date"
                      value={form.date}
                      onChange={(e) => setForm((prev) => ({ ...prev, date: e.target.value }))}
                      className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-1.5 text-xs focus:border-[#0B3B2E] focus:outline-none focus:ring-2 focus:ring-[#0B3B2E]/20"
                    />
                  </label>

                  <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-xs text-emerald-900">
                    <p className="font-black uppercase tracking-[0.16em] text-emerald-700">Account-Driven Context</p>
                    <p className="mt-1 leading-6">
                      Property and owner context are derived automatically from the selected accounts.
                      Select property-specific accounts (e.g. <span className="font-mono font-bold">2110-PARK</span>) to link a journal to a property and owner — no dropdown needed.
                    </p>
                  </div>
                </div>

                <div className="grid gap-4 md:grid-cols-2">
                  <div className="block">
                    <AppSelect
                      label="Debit Account"
                      value={form.debitAccount}
                      onChange={(val) => setForm((prev) => ({ ...prev, debitAccount: val ?? "" }))}
                      options={accountOptions}
                      placeholder="Search debit account..."
                      searchable
                      warning={selectedDebitAccountRecord?.isControl ? "⚠ Control account — post through the module to maintain reconciliation." : ""}
                    />
                  </div>

                  <div className="block">
                    <AppSelect
                      label="Credit Account"
                      value={form.creditAccount}
                      onChange={(val) => setForm((prev) => ({ ...prev, creditAccount: val ?? "" }))}
                      options={accountOptions}
                      placeholder="Search credit account..."
                      searchable
                      warning={selectedCreditAccountRecord?.isControl ? "⚠ Control account — post through the module to maintain reconciliation." : ""}
                    />
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <label className="block">
                  <span className="text-xs font-bold text-slate-700">Amount</span>
                  <input
                    type="number"
                    min="0"
                    value={form.amount}
                    onChange={(e) => setForm((prev) => ({ ...prev, amount: e.target.value }))}
                    className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-1.5 text-xs focus:border-[#0B3B2E] focus:outline-none focus:ring-2 focus:ring-[#0B3B2E]/20"
                  />
                </label>

                <label className="block">
                  <span className="text-xs font-bold text-slate-700">Reference</span>
                  <input
                    value={form.reference}
                    onChange={(e) => setForm((prev) => ({ ...prev, reference: e.target.value }))}
                    className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-1.5 text-xs focus:border-[#0B3B2E] focus:outline-none focus:ring-2 focus:ring-[#0B3B2E]/20"
                  />
                </label>

                <label className="block">
                  <span className="text-xs font-bold text-slate-700">Narration</span>
                  <textarea
                    rows={5}
                    value={form.narration}
                    onChange={(e) => setForm((prev) => ({ ...prev, narration: e.target.value }))}
                    className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-1.5 text-xs focus:border-[#0B3B2E] focus:outline-none focus:ring-2 focus:ring-[#0B3B2E]/20"
                  />
                </label>

                <label className="flex items-start gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-xs text-slate-700">
                  <input
                    type="checkbox"
                    checked={isInternalTransferJournal ? false : isForcedLandlordStatementJournal ? true : form.includeInLandlordStatement}
                    disabled={statementVisibilityLocked}
                    onChange={(e) =>
                      setForm((prev) => ({
                        ...prev,
                        includeInLandlordStatement: e.target.checked,
                      }))
                    }
                    className="mt-1"
                  />
                  <span>
                    Include in owner statement metadata
                    <span className="mt-1 block text-xs text-slate-500">
                      {isCompanyJournal
                        ? "Always off for company journals — never linked to any owner statement."
                        : isInternalTransferJournal
                        ? "Disabled for internal ledger transfers — same-company movements only."
                        : isForcedLandlordStatementJournal
                        ? "Locked on — this journal type always creates a clean owner addition or deduction."
                        : "Turn on only when exactly one side is Owner Remittance Payable. Debit = deduction. Credit = addition."}
                    </span>
                  </span>
                </label>

                <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-900">
                  <p className="font-black">Posting note</p>
                  <p className="mt-1 leading-6">{journalStructureHint}</p>
                  {!isCompanyJournal && (
                    <p className="mt-2 text-xs font-semibold text-amber-800">
                      Current selection: debit {debitTouchesLandlordPayable ? "touches" : "does not touch"} Owner Remittance Payable · credit {creditTouchesLandlordPayable ? "touches" : "does not touch"} Owner Remittance Payable.
                    </p>
                  )}
                  {controlAccountWarning.length > 0 && (
                    <div className="mt-2 space-y-1">
                      {controlAccountWarning.map((w, i) => (
                        <p key={i} className="text-xs font-bold text-amber-900">{w}</p>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            </div>

            <div className="sticky bottom-0 z-20 flex shrink-0 items-center justify-end gap-3 border-t border-slate-200 bg-white/95 px-6 py-4 backdrop-blur-sm">
              <button
                onClick={closeCreateModal}
                className="rounded-xl border border-slate-300 px-3 py-1.5 text-xs font-black text-slate-700"
              >
                Cancel
              </button>
              <button
                onClick={handleSaveJournal}
                disabled={!(editingJournalId ? canUpdateJournal : canCreateJournal) || saving}
                className="inline-flex items-center gap-2 rounded-xl bg-[#0B3B2E] px-3 py-1.5 text-xs font-black text-white disabled:opacity-60"
              >
                <FaPlus /> {saving ? "Saving..." : editingJournalId ? "Update Draft Journal" : "Save Draft Journal"}
              </button>
            </div>
          </div>
        </div>
      )}
    </DashboardLayout>
  );

};

export default JournalEntries;
