import React, { useCallback, useEffect, useMemo, useState } from "react";
import AppSelect from "../../components/common/AppSelect";
import { useLocation } from "react-router-dom";
import useDebounce from "../../hooks/useDebounce";
import {
  FaBook,
  FaBookOpen,
  FaCheck,
  FaEdit,
  FaFilter,
  FaPlus,
  FaRedoAlt,
  FaSearch,
  FaTimes,
  FaTrash,
  FaUndo,
} from "react-icons/fa";
import { useDispatch, useSelector } from "react-redux";
import { toast } from "react-toastify";
import DashboardLayout from "../../components/Layout/DashboardLayout";
import JournalEntriesDrawer from "../../components/Accounting/JournalEntriesDrawer";
import { isSelfManagingLandlordCompany } from "../../utils/companyModules";
import { selectCurrentCompany, selectCurrentUser, selectAllProperties } from "../../redux/selectors";
import { getProperties } from "../../redux/propertyRedux";
import {
  createJournalEntry,
  deleteJournalEntry,
  getChartOfAccounts,
  getJournalEntries,
  postJournalEntry,
  reverseJournalEntry,
  updateJournalEntry,
} from "../../redux/apiCalls";
import { hasCompanyPermission } from "../../utils/permissions";
import useScopedSessionDraft, { buildScopedDraftKey } from "../../hooks/useScopedSessionDraft";
import { useConfirm } from "../../context/ConfirmContext";
import { useTabState } from "../../hooks/useTabState";

const JOURNAL_TYPES = [
  {
    value: "general_manual_journal",
    label: "General Journal",
    description: "Standard double-entry journal. Select any two posting accounts from the Chart of Accounts. Property context is derived automatically from property-specific accounts (e.g. 2110-PARK).",
  },
  {
    value: "internal_account_transfer",
    label: "Internal Ledger Transfer",
    description: "Moves value between two ledger accounts within the same company. Never appears on any owner statement.",
  },
  {
    value: "landlord_credit_adjustment",
    label: "Owner / Creditor Credit",
    description: "Credits the Owner Remittance Payable account to raise an owner-facing addition. Select the property-specific remittance account (e.g. 2110-PARK) as the credit leg.",
  },
  {
    value: "landlord_debit_adjustment",
    label: "Owner / Creditor Debit",
    description: "Debits the Owner Remittance Payable account to post an owner-facing deduction. Select the property-specific remittance account (e.g. 2110-PARK) as the debit leg.",
  },
  {
    value: "property_expense_accrual",
    label: "Expense Accrual / Owner Deduction",
    description: "Accrues a property expense by debiting Owner Remittance Payable and crediting the accrual or offset account.",
  },
  {
    value: "company_journal",
    label: "Company Journal (Internal)",
    description: "Internal company-level journal with no property context. Use for head-office allocations, reclassifications, or company-wide adjustments. Never appears on any owner statement.",
  },
  {
    value: "payroll_posting",
    label: "Payroll Posting (HR)",
    description: "Auto-generated by the HR module when payroll is processed. Read-only in this view.",
  },
  {
    value: "statutory_payment",
    label: "Statutory Payment (HR)",
    description: "Auto-generated by the HR module for statutory remittances (PAYE, NSSF, NHIF). Read-only in this view.",
  },
];

const STATUS_STYLES = {
  draft: "bg-slate-100 text-slate-700 border-slate-200",
  posted: "bg-green-100 text-green-700 border-green-200",
  reversed: "bg-amber-100 text-amber-700 border-amber-200",
};

const APPROVAL_STYLES = {
  pending_review: "bg-amber-50 text-amber-700 border-amber-200",
  reviewed:       "bg-blue-50 text-blue-700 border-blue-200",
  approved:       "bg-emerald-50 text-emerald-700 border-emerald-200",
  rejected:       "bg-red-50 text-red-700 border-red-200",
};
const APPROVAL_LABELS = {
  pending_review: "Pending Review",
  reviewed:       "Reviewed",
  approved:       "Approved",
  rejected:       "Rejected",
};

const isLandlordPayableAccountRecord = (account = {}) => {
  const code = String(account?.code || account?.accountCode || "").trim().toUpperCase();
  const name = String(account?.name || account?.accountName || account?.title || "").trim().toLowerCase();
  return (
    code === "2110" ||
    /landlord remittance payable|landlord payable|owner payable|owner remittance payable/.test(name)
  );
};

const DEFAULT_PAGE_SIZE = 50;

const buildInitialForm = () => ({
  date: new Date().toISOString().split("T")[0],
  journalType: "general_manual_journal",
  debitAccount: "",
  creditAccount: "",
  amount: "",
  reference: "",
  narration: "",
  includeInLandlordStatement: false,
});

const JournalEntries = () => {
  const confirm = useConfirm();
  const dispatch = useDispatch();
  const location = useLocation();
  const isAccountsWorkspace = location.pathname.startsWith("/accounts/");
  const currentCompany = useSelector(selectCurrentCompany);
  const currentUser = useSelector(selectCurrentUser);
  const properties = useSelector(selectAllProperties);
  const canCreateJournal = hasCompanyPermission(currentUser || {}, currentCompany, "journals", "create", "accounts");
  const canUpdateJournal = hasCompanyPermission(currentUser || {}, currentCompany, "journals", "update", "accounts");
  const canPostJournal = hasCompanyPermission(currentUser || {}, currentCompany, "journals", "process", "accounts");
  const canReverseJournal = hasCompanyPermission(currentUser || {}, currentCompany, "journals", "reverse", "accounts");
  const canDeleteJournal = hasCompanyPermission(currentUser || {}, currentCompany, "journals", "delete", "accounts");
  const isLandlordWorkspace = useMemo(
    () => isSelfManagingLandlordCompany(currentCompany || currentUser?.company || null),
    [currentCompany, currentUser?.company]
  );

  const journalDraftKey = buildScopedDraftKey({
    page: "journal-entries",
    companyId: currentCompany?._id,
    userId: currentUser?._id || currentUser?.id || currentUser?.email,
  });
  const [journalDraft, setJournalDraft] = useScopedSessionDraft(journalDraftKey, {
    filters: {
      search: "",
      status: "all",
      journalType: "all",
      propertyId: "all",
    },
  });

  const [journals, setJournals] = useState([]);
  const [accounts, setAccounts] = useState([]);
  const [loading, setLoading] = useState(false);
  const [rowActionKey, setRowActionKey] = useState("");
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [editingJournalId, setEditingJournalId] = useState("");
  const [glJournal, setGlJournal] = useState(null);
  const [saving, setSaving] = useState(false);

  const filters = journalDraft.filters || { search: "", status: "all", journalType: "all", propertyId: "all" };
  const debouncedSearch = useDebounce(filters.search, 400);
  const setFilters = (value) => setJournalDraft((prev) => ({ ...prev, filters: typeof value === "function" ? value(prev.filters || filters) : value }));
  const setFilter = (key) => (e) => setFilters((prev) => ({ ...prev, [key]: e.target.value }));

  const [form, setForm] = useState(buildInitialForm);
  const [pageSize, setPageSize] = useTabState("/accounts/journals:pageSize", DEFAULT_PAGE_SIZE);
  const [currentPage, setCurrentPage] = useTabState("/accounts/journals:currentPage", 1);
  const [serverTotal, setServerTotal] = useState(0);
  const [serverPages, setServerPages] = useState(1);

  useEffect(() => {
    if (currentCompany?._id) dispatch(getProperties({ business: currentCompany._id }));
  }, [dispatch, currentCompany?._id]);

  const propertyOptions = useMemo(
    () => properties.map((p) => ({ value: p._id, label: p.propertyName || p.name || "Property" })),
    [properties]
  );

  useEffect(() => {
    const loadAccounts = async () => {
      if (!currentCompany?._id) return;
      try {
        const rows = await getChartOfAccounts({ business: currentCompany._id });
        setAccounts(
          Array.isArray(rows)
            ? rows.filter((row) => row?.isPosting !== false && row?.isHeader !== true)
            : []
        );
      } catch (error) {
        toast.error(
          error?.response?.data?.error ||
            error?.response?.data?.message ||
            "Failed to load chart of accounts"
        );
      }
    };

    loadAccounts();
  }, [currentCompany?._id]);

  const loadJournals = useCallback(async () => {
    if (!currentCompany?._id) return;
    setLoading(true);
    try {
      const { data: rows, total, pages } = await getJournalEntries({
        business: currentCompany._id,
        company: currentCompany._id,
        ...(isAccountsWorkspace ? {} : { excludeSourceModules: "hr,carwash" }),
        ...filters,
        search: debouncedSearch,
        page: currentPage,
        limit: pageSize,
      });
      setJournals(Array.isArray(rows) ? rows : []);
      setServerTotal(total ?? 0);
      setServerPages(pages ?? 1);
    } catch (error) {
      toast.error(error?.response?.data?.message || "Failed to load journal entries");
    } finally {
      setLoading(false);
    }
  }, [currentCompany?._id, isAccountsWorkspace, debouncedSearch, filters.status, filters.journalType, filters.propertyId, currentPage, pageSize]);

  useEffect(() => { loadJournals(); }, [loadJournals]);

  const totals = useMemo(() => {
    return journals.reduce(
      (acc, item) => {
        const amount = Number(item.amount || 0);
        acc.total += amount;
        if (item.status === "draft") acc.draft += amount;
        if (item.status === "posted") acc.posted += amount;
        if (item.status === "reversed") acc.reversed += amount;
        return acc;
      },
      { total: 0, draft: 0, posted: 0, reversed: 0 }
    );
  }, [journals]);


  const totalPages = Math.max(1, serverPages);
  const safeCurrentPage = Math.min(currentPage, totalPages);
  const currentPageRows = journals;

  useEffect(() => {
    setCurrentPage(1);
  }, [debouncedSearch, filters.status, filters.journalType, filters.propertyId, pageSize]);

  const accountOptions = useMemo(
    () =>
      accounts.map((a) => ({
        value: a._id,
        label: `${a.code} – ${a.name}`,
        description: [
          a.type ? a.type.charAt(0).toUpperCase() + a.type.slice(1) : "",
          a.subGroup || a.group || "",
        ]
          .filter(Boolean)
          .join(" · "),
        isControl: Boolean(a.isControl),
      })),
    [accounts]
  );

  const selectedDebitAccountRecord = useMemo(
    () => accounts.find((account) => String(account?._id || "") === String(form.debitAccount || "")) || null,
    [accounts, form.debitAccount]
  );

  const selectedCreditAccountRecord = useMemo(
    () => accounts.find((account) => String(account?._id || "") === String(form.creditAccount || "")) || null,
    [accounts, form.creditAccount]
  );

  const getJournalTypePresentation = (journalType) =>
    JOURNAL_TYPES.find((type) => type.value === journalType) || JOURNAL_TYPES[0];

  const activeJournalTypePresentation = useMemo(
    () => getJournalTypePresentation(form.journalType),
    [form.journalType]
  );

  const isCompanyJournal = form.journalType === "company_journal";
  const isInternalTransferJournal = form.journalType === "internal_account_transfer";
  const isForcedLandlordStatementJournal =
    !isCompanyJournal &&
    (form.journalType === "landlord_credit_adjustment" ||
      form.journalType === "landlord_debit_adjustment" ||
      form.journalType === "property_expense_accrual");
  const debitTouchesLandlordPayable = !isCompanyJournal && isLandlordPayableAccountRecord(selectedDebitAccountRecord);
  const creditTouchesLandlordPayable = !isCompanyJournal && isLandlordPayableAccountRecord(selectedCreditAccountRecord);
  const statementVisibilityLocked = isCompanyJournal || isInternalTransferJournal || isForcedLandlordStatementJournal;
  const controlAccountWarning = useMemo(() => {
    const warnings = [];
    if (selectedDebitAccountRecord?.isControl) warnings.push(`Dr: "${selectedDebitAccountRecord.name}" is a control account — module transactions post here automatically. Use only for corrections and manual fixes.`);
    if (selectedCreditAccountRecord?.isControl) warnings.push(`Cr: "${selectedCreditAccountRecord.name}" is a control account — module transactions post here automatically. Use only for corrections and manual fixes.`);
    return warnings;
  }, [selectedDebitAccountRecord, selectedCreditAccountRecord]);

  const journalStructureHint = useMemo(() => {
    if (form.journalType === "company_journal") {
      return "Company journals are internal-only. No property or owner context is attached. These entries never appear on any owner statement.";
    }
    if (form.journalType === "landlord_credit_adjustment") {
      return "Select the property-specific Owner Remittance Payable (e.g. 2110-PARK) as the credit leg and a balancing account as the debit. This creates one clean owner statement addition.";
    }
    if (form.journalType === "landlord_debit_adjustment") {
      return "Select the property-specific Owner Remittance Payable (e.g. 2110-PARK) as the debit leg and a balancing account as the credit. This creates one clean owner statement deduction.";
    }
    if (form.journalType === "property_expense_accrual") {
      return "Debit the Owner Remittance Payable account (e.g. 2110-PARK) and credit the accrual or offset account. The property context is derived automatically from the account.";
    }
    if (form.journalType === "internal_account_transfer") {
      return "Internal transfers stay inside the same company only and must not use Owner Remittance Payable or appear on any owner statement.";
    }
    if (form.includeInLandlordStatement) {
      return "Statement-visible general journals must touch Owner Remittance Payable on exactly one side. Debit = deduction. Credit = addition.";
    }
    return "The account selection carries all context — select property-specific accounts (e.g. 2110-PARK) to automatically link to a property and owner.";
  }, [form.includeInLandlordStatement, form.journalType]);

  const applyJournalTypeDefaults = (journalType) => {
    const landlordStatementJournal =
      journalType === "landlord_credit_adjustment" ||
      journalType === "landlord_debit_adjustment" ||
      journalType === "property_expense_accrual";

    setForm((prev) => ({
      ...prev,
      journalType,
      includeInLandlordStatement:
        journalType === "company_journal" || journalType === "internal_account_transfer"
          ? false
          : landlordStatementJournal,
    }));
  };

  const resetForm = () => {
    setEditingJournalId("");
    setForm(buildInitialForm());
  };

  const openCreateModal = () => {
    if (!canCreateJournal) {
      toast.warning("You do not have permission to create journals");
      return;
    }
    setEditingJournalId("");
    setForm(buildInitialForm());
    setShowCreateModal(true);
  };

  const openEditModal = (journal) => {
    if (!canUpdateJournal) {
      toast.warning("You do not have permission to edit journals");
      return;
    }
    if (journal?.status !== "draft") {
      toast.info("Only draft journals can be edited directly. Reverse posted journals and recreate them if needed.");
      return;
    }

    setEditingJournalId(String(journal._id || ""));
    setForm({
      date: journal?.date ? new Date(journal.date).toISOString().split("T")[0] : new Date().toISOString().split("T")[0],
      journalType: journal?.journalType || "general_manual_journal",
      debitAccount: journal?.debitAccount?._id || journal?.debitAccount || "",
      creditAccount: journal?.creditAccount?._id || journal?.creditAccount || "",
      amount: journal?.amount || "",
      reference: journal?.reference || "",
      narration: journal?.narration || "",
      includeInLandlordStatement: Boolean(journal?.includeInLandlordStatement),
    });
    setShowCreateModal(true);
  };

  const closeCreateModal = () => {
    setShowCreateModal(false);
    resetForm();
  };


  const handleSaveJournal = async () => {
    if (!(editingJournalId ? canUpdateJournal : canCreateJournal)) {
      toast.warning(editingJournalId ? "You do not have permission to update journals" : "You do not have permission to create journals");
      return;
    }
    if (!currentCompany?._id) {
      toast.warning("Please select a company first");
      return;
    }

    if (!form.debitAccount) {
      toast.warning("Debit account is required");
      return;
    }

    if (!form.creditAccount) {
      toast.warning("Credit account is required");
      return;
    }

    if (form.debitAccount === form.creditAccount) {
      toast.warning("Debit and credit accounts must be different");
      return;
    }

    if (!form.amount || Number(form.amount) <= 0) {
      toast.warning("Amount must be greater than zero");
      return;
    }

    if (isInternalTransferJournal && (debitTouchesLandlordPayable || creditTouchesLandlordPayable)) {
      toast.warning("Internal ledger transfers cannot use Landlord Remittance Payable.");
      return;
    }

    if (form.journalType === "landlord_credit_adjustment" && (!creditTouchesLandlordPayable || debitTouchesLandlordPayable)) {
      toast.warning("Landlord Credit Adjustment must credit Landlord Remittance Payable.");
      return;
    }

    if (["landlord_debit_adjustment", "property_expense_accrual"].includes(form.journalType) && (!debitTouchesLandlordPayable || creditTouchesLandlordPayable)) {
      toast.warning(
        form.journalType === "property_expense_accrual"
          ? "Property Expense / Landlord Deduction must debit Landlord Remittance Payable."
          : "Landlord Debit Adjustment must debit Landlord Remittance Payable."
      );
      return;
    }

    if (
      form.journalType === "general_manual_journal" &&
      form.includeInLandlordStatement &&
      debitTouchesLandlordPayable === creditTouchesLandlordPayable
    ) {
      toast.warning("Statement-visible general journals must touch Landlord Remittance Payable on exactly one side.");
      return;
    }

    const payload = {
      business: currentCompany._id,
      company: currentCompany._id,
      date: form.date,
      journalType: form.journalType,
      debitAccount: form.debitAccount,
      creditAccount: form.creditAccount,
      amount: Number(form.amount),
      reference: form.reference,
      narration: form.narration,
      includeInLandlordStatement: isCompanyJournal || isInternalTransferJournal
        ? false
        : isForcedLandlordStatementJournal
        ? true
        : Boolean(form.includeInLandlordStatement),
      sourceModule: isAccountsWorkspace ? "accounts" : "propertyManagement",
    };

    setSaving(true);
    try {
      const saved = editingJournalId
        ? await updateJournalEntry(editingJournalId, payload)
        : await createJournalEntry(payload);

      setJournals((prev) =>
        editingJournalId
          ? prev.map((row) => (row._id === editingJournalId ? saved : row))
          : [saved, ...prev]
      );
      toast.success(
        editingJournalId
          ? `Journal ${saved?.journalNo || ""} updated`
          : `Journal ${saved?.journalNo || ""} created`
      );
      closeCreateModal();
    } catch (error) {
      toast.error(
        error?.response?.data?.message ||
          (editingJournalId ? "Failed to update journal" : "Failed to create journal")
      );
    } finally {
      setSaving(false);
    }
  };

  const handlePostJournal = async (journal) => {
    if (!canPostJournal) {
      toast.warning("You do not have permission to post journals");
      return;
    }
    setRowActionKey(`${journal._id}:post`);
    try {
      const updated = await postJournalEntry(journal._id, {
        business: currentCompany?._id,
        company: currentCompany?._id,
      });
      setJournals((prev) => prev.map((row) => (row._id === journal._id ? updated : row)));
      toast.success(`Journal ${updated?.journalNo || ""} posted`);
    } catch (error) {
      toast.error(error?.response?.data?.message || "Failed to post journal");
    } finally {
      setRowActionKey("");
    }
  };

  const handleReverseJournal = async (journal) => {
    if (!canReverseJournal) {
      toast.warning("You do not have permission to reverse journals");
      return;
    }
    const ok = await confirm({ title: "Reverse Journal", message: `Reverse journal ${journal.journalNo}? A reversing entry will be created.`, confirmText: "Reverse" });
    if (!ok) return;

    setRowActionKey(`${journal._id}:reverse`);
    try {
      const updated = await reverseJournalEntry(journal._id, {
        business: currentCompany?._id,
        company: currentCompany?._id,
        reason: `Journal ${journal.journalNo} reversed`,
      });
      setJournals((prev) => prev.map((row) => (row._id === journal._id ? updated : row)));
      toast.success(`Journal ${updated?.journalNo || ""} reversed`);
    } catch (error) {
      toast.error(error?.response?.data?.message || "Failed to reverse journal");
    } finally {
      setRowActionKey("");
    }
  };

  const handleDeleteJournal = async (journal) => {
    if (!canDeleteJournal) {
      toast.warning("You do not have permission to delete journals");
      return;
    }
    const ok = await confirm({ title: "Delete Journal", message: `Delete draft journal ${journal.journalNo}?`, confirmText: "Delete", isDangerous: true });
    if (!ok) return;

    setRowActionKey(`${journal._id}:delete`);
    try {
      await deleteJournalEntry(journal._id, {
        business: currentCompany?._id,
        company: currentCompany?._id,
      });
      setJournals((prev) => prev.filter((row) => row._id !== journal._id));
      toast.success("Journal deleted");
    } catch (error) {
      toast.error(error?.response?.data?.message || "Failed to delete journal");
    } finally {
      setRowActionKey("");
    }
  };

  return (
    <DashboardLayout lockContentScroll>
      <div className="flex h-full min-h-0 flex-col overflow-hidden bg-gradient-to-br from-slate-50 via-white to-slate-100 p-1 sm:p-2">
        <div className="mx-auto flex h-full w-full max-w-none flex-col overflow-hidden">

          <div className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-lg border border-slate-200 bg-white shadow-lg">
            <div className="flex-none sticky top-0 z-30 border-b border-gray-200 bg-white shadow-sm">
              <div className="filter-bar flex items-center gap-1 overflow-x-auto px-2 py-1.5">
                <span className="shrink-0 rounded border border-blue-200 bg-blue-50 px-1.5 py-0.5 text-[9px] font-bold text-blue-700">Journals: {serverTotal}</span>
                <span className="shrink-0 rounded border border-blue-200 bg-blue-50 px-1.5 py-0.5 text-[9px] font-bold text-blue-700">Total: KES {totals.total.toLocaleString()}</span>
                <span className="shrink-0 rounded border border-emerald-200 bg-emerald-50 px-1.5 py-0.5 text-[9px] font-bold text-emerald-700">Posted: KES {totals.posted.toLocaleString()}</span>
                <span className="shrink-0 rounded border border-amber-200 bg-amber-50 px-1.5 py-0.5 text-[9px] font-bold text-amber-700">Draft: {journals.filter((j) => j.status === "draft").length}</span>
                <div className="mx-0.5 h-4 w-px shrink-0 bg-slate-200" />
                <div className="relative shrink-0">
                  <FaSearch className="absolute left-2 top-1/2 -translate-y-1/2 text-[10px] text-slate-400" />
                  <input
                    value={filters.search}
                    onChange={setFilter("search")}
                    placeholder="Journal no, reference, narration"
                    className="h-7 w-44 rounded border border-slate-200 bg-white pl-6 pr-2 text-xs focus:outline-none focus:ring-1 focus:ring-[#0B3B2E]/20"
                  />
                </div>
                <select value={filters.status} onChange={setFilter("status")} className="h-7 shrink-0 rounded border border-slate-200 bg-white px-2 text-xs appearance-none focus:outline-none focus:ring-1 focus:ring-[#0B3B2E]/20">
                  <option value="all">All Statuses</option>
                  <option value="draft">Draft</option>
                  <option value="posted">Posted</option>
                  <option value="reversed">Reversed</option>
                </select>
                <select value={filters.journalType} onChange={setFilter("journalType")} className="h-7 shrink-0 rounded border border-slate-200 bg-white px-2 text-xs appearance-none focus:outline-none focus:ring-1 focus:ring-[#0B3B2E]/20">
                  <option value="all">All Journal Types</option>
                  {JOURNAL_TYPES.map((type) => (
                    <option key={type.value} value={type.value}>{getJournalTypePresentation(type.value)?.label || type.label}</option>
                  ))}
                </select>
                <select value={filters.propertyId} onChange={setFilter("propertyId")} className="h-7 shrink-0 rounded border border-slate-200 bg-white px-2 text-xs appearance-none focus:outline-none focus:ring-1 focus:ring-[#0B3B2E]/20">
                  <option value="all">All Properties</option>
                  {propertyOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}
                </select>
                <button onClick={() => setFilters({ search: "", status: "all", journalType: "all", propertyId: "all" })} className="h-7 shrink-0 flex items-center gap-1 rounded border border-slate-200 bg-white px-2.5 text-xs font-semibold text-slate-700 hover:bg-slate-50">
                  <FaFilter size={9} /> Reset
                </button>
                <button onClick={loadJournals} className="h-7 shrink-0 flex items-center gap-1 rounded border border-slate-200 bg-white px-2.5 text-xs font-semibold text-slate-700 hover:bg-slate-50"><FaRedoAlt size={9} /></button>
                <button onClick={openCreateModal} className="h-7 shrink-0 flex items-center gap-1 rounded bg-[#0B3B2E] px-2.5 text-xs font-semibold text-white hover:bg-[#0A3127]"><FaPlus size={9} /> New Journal</button>
              </div>
            </div>

            <div className="min-h-0 flex-1 overflow-auto overscroll-contain">
              <table className="w-full min-w-[1100px] text-[11px] border-collapse">
                <thead className="sticky top-0 z-10 bg-[#0B3B2E] text-white">
                  <tr>
                    <th className="px-3 py-1 text-left font-bold border-r border-white/10">Journal #</th>
                    <th className="px-3 py-1 text-left font-bold border-r border-white/10">Date</th>
                    <th className="px-3 py-1 text-left font-bold border-r border-white/10">Type</th>
                    <th className="px-3 py-1 text-left font-bold border-r border-white/10">Debit Account</th>
                    <th className="px-3 py-1 text-left font-bold border-r border-white/10">Credit Account</th>
                    <th className="px-3 py-1 text-right font-bold border-r border-white/10">Amount (KES)</th>
                    <th className="px-3 py-1 text-center font-bold border-r border-white/10">Status</th>
                    <th className="px-3 py-1 text-right font-bold">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {loading ? (
                    <tr><td colSpan={8} className="px-4 py-10 text-center text-slate-500">Loading journals...</td></tr>
                  ) : journals.length === 0 ? (
                    <tr><td colSpan={8} className="px-4 py-10 text-center text-slate-500">No journals found.</td></tr>
                  ) : (
                    currentPageRows.map((journal, index) => {
                      const busyPost = rowActionKey === `${journal._id}:post`;
                      const busyReverse = rowActionKey === `${journal._id}:reverse`;
                      const busyDelete = rowActionKey === `${journal._id}:delete`;
                      return (
                        <tr key={journal._id} className={`cursor-pointer border-b border-gray-100 transition-colors ${index % 2 === 0 ? "bg-white hover:bg-blue-50/40" : "bg-slate-50/60 hover:bg-blue-50/40"}`}>
                          <td className="px-3 py-1 border-r border-gray-100 font-bold text-slate-900 whitespace-nowrap" title={[journal.narration, journal.reference, journal.property?.propertyName || journal.property?.name, journal.landlord?.landlordName || journal.landlord?.name].filter(Boolean).join(" | ")}>{journal.journalNo}</td>
                          <td className="px-3 py-1 border-r border-gray-100 text-slate-700 whitespace-nowrap">{journal.date ? new Date(journal.date).toLocaleDateString("en-GB") : "—"}</td>
                          <td className="px-3 py-1 border-r border-gray-100 text-slate-700 max-w-[130px] truncate">{getJournalTypePresentation(journal.journalType)?.label || journal.journalType}</td>
                          <td className="px-3 py-1 border-r border-gray-100 text-slate-700 max-w-[200px] truncate" title={journal.debitAccount?.name}><span className="font-mono font-bold text-slate-400 mr-1">{journal.debitAccount?.code}</span>{journal.debitAccount?.name || "—"}</td>
                          <td className="px-3 py-1 border-r border-gray-100 text-slate-700 max-w-[200px] truncate" title={journal.creditAccount?.name}><span className="font-mono font-bold text-slate-400 mr-1">{journal.creditAccount?.code}</span>{journal.creditAccount?.name || "—"}</td>
                          <td className="px-3 py-1 border-r border-gray-100 text-right font-bold text-slate-900">{Number(journal.amount || 0).toLocaleString()}</td>
                          <td className="px-3 py-1 border-r border-gray-100 text-center" title={journal.approvalStatus && journal.approvalStatus !== "not_required" ? (APPROVAL_LABELS[journal.approvalStatus] || journal.approvalStatus) : undefined}>
                            <span className={`inline-flex rounded-full border px-2 py-0.5 text-[10px] font-bold ${STATUS_STYLES[journal.status] || STATUS_STYLES.draft}`}>{journal.status}</span>
                          </td>
                          <td className="px-3 py-1 text-right">
                            <div className="flex justify-end gap-1" onClick={(e) => e.stopPropagation()}>
                              {journal.status === "posted" && (
                                <button onClick={() => setGlJournal(journal)} className="rounded p-1 text-teal-600 hover:bg-teal-50 hover:text-teal-800" title="View GL Entries"><FaBook size={12} /></button>
                              )}
                              {journal.status === "draft" && canUpdateJournal && (
                                <button onClick={() => openEditModal(journal)} disabled={!canUpdateJournal || !!rowActionKey} className="rounded p-1 text-blue-600 hover:bg-blue-50 hover:text-blue-800 disabled:opacity-40" title="Edit"><FaEdit size={12} /></button>
                              )}
                              {journal.status === "draft" && canPostJournal && (
                                <button onClick={() => handlePostJournal(journal)} disabled={!canPostJournal || !!rowActionKey} className="rounded p-1 text-emerald-600 hover:bg-emerald-50 hover:text-emerald-800 disabled:opacity-40" title={busyPost ? "Posting…" : "Post Journal"}><FaCheck size={12} /></button>
                              )}
                              {journal.status === "posted" && canReverseJournal && (
                                <button onClick={() => handleReverseJournal(journal)} disabled={!canReverseJournal || !!rowActionKey} className="rounded p-1 text-amber-600 hover:bg-amber-50 hover:text-amber-800 disabled:opacity-40" title={busyReverse ? "Reversing…" : "Reverse"}><FaUndo size={12} /></button>
                              )}
                              {journal.status === "draft" && canDeleteJournal && (
                                <button onClick={() => handleDeleteJournal(journal)} disabled={!canDeleteJournal || !!rowActionKey} className="rounded p-1 text-rose-600 hover:bg-rose-50 hover:text-rose-800 disabled:opacity-40" title={busyDelete ? "Deleting…" : "Delete"}><FaTrash size={12} /></button>
                              )}
                            </div>
                          </td>
                        </tr>
                      );
                    })
                  )}
                </tbody>
              </table>
            </div>
            <div className="flex flex-shrink-0 flex-wrap items-center justify-between gap-3 border-t border-slate-200 bg-white px-3 py-2 text-xs text-slate-600">
              <div className="font-semibold">Showing <span className="font-bold text-slate-900">{journals.length === 0 ? 0 : (safeCurrentPage - 1) * pageSize + 1}</span> to <span className="font-bold text-slate-900">{Math.min(safeCurrentPage * pageSize, serverTotal)}</span> of <span className="font-bold text-slate-900">{serverTotal}</span> journal(s)</div>
              <div className="flex items-center gap-3"><div className="flex items-center gap-1.5"><span className="font-semibold text-slate-500">Per page:</span><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setCurrentPage(1); }} className="h-7 rounded border border-slate-200 bg-slate-50 px-2 text-xs font-bold text-slate-700 focus:border-[#0B3B2E] focus:outline-none">{[25, 50, 100, 200].map((n) => <option key={n} value={n}>{n}</option>)}</select></div><button onClick={() => setCurrentPage((prev) => Math.max(1, prev - 1))} disabled={safeCurrentPage === 1} className="rounded-lg border border-slate-300 px-3 py-1 font-semibold hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50">Previous</button><span className="font-semibold text-slate-700">Page {safeCurrentPage} of {totalPages}</span><button onClick={() => setCurrentPage((prev) => Math.min(totalPages, prev + 1))} disabled={safeCurrentPage === totalPages} className="rounded-lg border border-slate-300 px-3 py-1 font-semibold hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50">Next</button></div>
            </div>
          </div>
        </div>
      </div>

      {showCreateModal && (
        <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-900/60 p-4 backdrop-blur-sm">
          <div className="flex w-full max-w-3xl max-h-[92vh] flex-col overflow-hidden bg-white shadow-2xl">

            {/* ── Header ── */}
            <div className="flex shrink-0 items-start justify-between bg-[#0B3B2E] px-5 py-4">
              <div>
                <p className="text-[10px] font-bold uppercase tracking-[0.18em] text-emerald-400">Financial Accounts</p>
                <h3 className="mt-0.5 text-lg font-black text-white">
                  {editingJournalId ? "Edit Draft Journal" : "Create Journal Entry"}
                </h3>
                <p className="mt-1 text-[11px] text-emerald-100/70">
                  {editingJournalId
                    ? "Only draft journals can be edited. Posted journals must be reversed."
                    : "Save as draft, then post from the journal list."}
                </p>
              </div>
              <button onClick={closeCreateModal} className="mt-0.5 text-white/50 transition hover:text-white">
                <FaTimes size={14} />
              </button>
            </div>

            {/* ── Body ── */}
            <div className="flex min-h-0 flex-1 overflow-hidden">

              {/* Left — form */}
              <div className="flex-1 overflow-y-auto px-5 py-5 space-y-4">

                {/* Journal Type */}
                <div>
                  <p className="mb-1.5 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">Journal Type</p>
                  <AppSelect
                    value={form.journalType}
                    onChange={(val) => applyJournalTypeDefaults(val ?? "general_manual_journal")}
                    options={JOURNAL_TYPES.map((t) => ({
                      value: t.value,
                      label: getJournalTypePresentation(t.value)?.label || t.label,
                      description: t.description,
                    }))}
                  />
                  <p className="mt-1.5 text-[11px] text-slate-400">{activeJournalTypePresentation.shortDescription ?? activeJournalTypePresentation.description?.split(".")[0]}</p>
                </div>

                {/* Date */}
                <div>
                  <p className="mb-1.5 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">Journal Date</p>
                  <input
                    type="date"
                    value={form.date}
                    onChange={(e) => setForm((prev) => ({ ...prev, date: e.target.value }))}
                    className="w-full border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-[#0B3B2E]"
                  />
                </div>

                {/* Debit Account */}
                <div>
                  <p className="mb-1.5 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">Debit Account</p>
                  <AppSelect
                    value={form.debitAccount}
                    onChange={(val) => setForm((prev) => ({ ...prev, debitAccount: val ?? "" }))}
                    options={accountOptions}
                    placeholder="Search debit account..."
                    searchable
                    warning={selectedDebitAccountRecord?.isControl ? "ℹ Control account — module entries post here automatically. Manual entries are allowed for corrections." : ""}
                  />
                </div>

                {/* Credit Account */}
                <div>
                  <p className="mb-1.5 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">Credit Account</p>
                  <AppSelect
                    value={form.creditAccount}
                    onChange={(val) => setForm((prev) => ({ ...prev, creditAccount: val ?? "" }))}
                    options={accountOptions}
                    placeholder="Search credit account..."
                    searchable
                    warning={selectedCreditAccountRecord?.isControl ? "ℹ Control account — module entries post here automatically. Manual entries are allowed for corrections." : ""}
                  />
                </div>

                {/* Amount */}
                <div>
                  <p className="mb-1.5 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">Amount (KES)</p>
                  <input
                    type="number"
                    min="0"
                    value={form.amount}
                    onChange={(e) => setForm((prev) => ({ ...prev, amount: e.target.value }))}
                    placeholder="0.00"
                    className="w-full border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-[#0B3B2E]"
                  />
                </div>

                {/* Reference */}
                <div>
                  <p className="mb-1.5 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">Reference</p>
                  <input
                    value={form.reference}
                    onChange={(e) => setForm((prev) => ({ ...prev, reference: e.target.value }))}
                    placeholder="e.g. INV-001, CHQ-202"
                    className="w-full border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none placeholder:text-slate-300 focus:border-[#0B3B2E]"
                  />
                </div>

                {/* Narration */}
                <div>
                  <p className="mb-1.5 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">Narration</p>
                  <textarea
                    rows={3}
                    value={form.narration}
                    onChange={(e) => setForm((prev) => ({ ...prev, narration: e.target.value }))}
                    placeholder="Brief description of this journal entry…"
                    className="w-full resize-none border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none placeholder:text-slate-300 focus:border-[#0B3B2E]"
                  />
                </div>

                {/* Include in statement */}
                <label className="flex cursor-pointer items-start gap-3 border border-slate-200 bg-slate-50 px-4 py-3">
                  <input
                    type="checkbox"
                    checked={isInternalTransferJournal ? false : isForcedLandlordStatementJournal ? true : form.includeInLandlordStatement}
                    disabled={statementVisibilityLocked}
                    onChange={(e) => setForm((prev) => ({ ...prev, includeInLandlordStatement: e.target.checked }))}
                    className="mt-0.5"
                  />
                  <span className="text-xs text-slate-700">
                    <span className="font-bold">Include in owner statement metadata</span>
                    <span className="mt-0.5 block text-slate-500">
                      {isCompanyJournal
                        ? "Always off for company journals."
                        : isInternalTransferJournal
                        ? "Disabled for internal transfers."
                        : isForcedLandlordStatementJournal
                        ? "Locked on — this journal type always affects owner statements."
                        : "Turn on only when one side is Owner Remittance Payable."}
                    </span>
                  </span>
                </label>

              </div>

              {/* Right — live preview */}
              <div className="w-[240px] shrink-0 overflow-y-auto border-l border-slate-200 bg-slate-50 px-4 py-4 space-y-3">

                {/* Amount hero */}
                <div className="bg-[#0B3B2E] px-4 py-3 text-white">
                  <p className="text-[9px] font-bold uppercase tracking-[0.18em] text-emerald-400">Amount</p>
                  <p className="mt-1 text-2xl font-black tabular-nums leading-tight">
                    {form.amount && Number(form.amount) > 0
                      ? `${Number(form.amount).toLocaleString("en-KE", { minimumFractionDigits: 2 })}`
                      : <span className="text-xl text-emerald-600">—</span>}
                  </p>
                  <p className="mt-0.5 text-[10px] text-emerald-400">KES</p>
                </div>

                {/* T-account preview */}
                <div className="border border-slate-200 bg-white p-3">
                  <p className="mb-2 text-[9px] font-bold uppercase tracking-[0.16em] text-slate-400">Journal Preview</p>
                  <div className="space-y-1.5">
                    <div className="flex items-start gap-1.5 bg-slate-50 px-2 py-1.5">
                      <span className="mt-0.5 shrink-0 bg-blue-100 px-1 py-0.5 text-[8px] font-black text-blue-700">DR</span>
                      <span className="min-w-0 flex-1 text-[10px] font-semibold text-slate-700 break-words leading-snug">
                        {selectedDebitAccountRecord
                          ? `${selectedDebitAccountRecord.code} – ${selectedDebitAccountRecord.name}`
                          : <span className="italic text-slate-400">Debit account</span>}
                      </span>
                    </div>
                    <div className="ml-3 flex items-start gap-1.5 bg-slate-50 px-2 py-1.5">
                      <span className="mt-0.5 shrink-0 bg-emerald-100 px-1 py-0.5 text-[8px] font-black text-emerald-700">CR</span>
                      <span className="min-w-0 flex-1 text-[10px] font-semibold text-slate-700 break-words leading-snug">
                        {selectedCreditAccountRecord
                          ? `${selectedCreditAccountRecord.code} – ${selectedCreditAccountRecord.name}`
                          : <span className="italic text-slate-400">Credit account</span>}
                      </span>
                    </div>
                  </div>
                  {form.amount && Number(form.amount) > 0 && (
                    <div className="mt-2 flex justify-between border-t border-slate-100 pt-2 text-[10px] font-bold">
                      <span className="text-blue-600">DR {Number(form.amount).toLocaleString("en-KE", { minimumFractionDigits: 2 })}</span>
                      <span className="text-emerald-600">CR {Number(form.amount).toLocaleString("en-KE", { minimumFractionDigits: 2 })}</span>
                    </div>
                  )}
                </div>

                {/* Posting note */}
                <div className="border border-amber-200 bg-amber-50 p-3">
                  <p className="text-[9px] font-bold uppercase tracking-[0.16em] text-amber-600">Posting Note</p>
                  <p className="mt-1 text-[10px] text-amber-900">{journalStructureHint?.split(".")[0]}.</p>
                  {!isCompanyJournal && (
                    <p className="mt-1 text-[10px] font-semibold text-amber-800">
                      Dr {debitTouchesLandlordPayable ? "✓" : "✗"} payable · Cr {creditTouchesLandlordPayable ? "✓" : "✗"} payable
                    </p>
                  )}
                  {controlAccountWarning.length > 0 && (
                    <div className="mt-1.5 border border-blue-200 bg-blue-50 px-2 py-1.5 space-y-0.5">
                      {controlAccountWarning.map((w, i) => (
                        <p key={i} className="text-[10px] font-semibold text-blue-800">{w}</p>
                      ))}
                    </div>
                  )}
                </div>

              </div>
            </div>

            {/* ── Footer ── */}
            <div className="flex shrink-0 gap-3 border-t border-slate-200 px-5 py-4">
              <button
                type="button"
                onClick={closeCreateModal}
                className="flex-1 border border-slate-300 py-2 text-sm font-bold text-slate-700 transition hover:bg-slate-50"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleSaveJournal}
                disabled={!(editingJournalId ? canUpdateJournal : canCreateJournal) || saving}
                className="flex-1 flex items-center justify-center gap-2 bg-[#0B3B2E] py-2 text-sm font-black text-white transition hover:bg-[#0A3127] disabled:opacity-50"
              >
                <FaPlus size={10} /> {saving ? "Saving…" : editingJournalId ? "Update Draft Journal" : "Save Draft Journal"}
              </button>
            </div>
          </div>
        </div>
      )}
      <JournalEntriesDrawer
        open={!!glJournal}
        onClose={() => setGlJournal(null)}
        title="Journal Entry"
        transactionRef={glJournal?.journalNo}
        date={glJournal?.date ? new Date(glJournal.date).toLocaleDateString("en-GB") : undefined}
        amount={glJournal?.amount}
        status={glJournal?.status}
        statusColors={STATUS_STYLES[glJournal?.status] || STATUS_STYLES.draft}
        contextFields={glJournal ? [
          { label: "Type",      value: getJournalTypePresentation(glJournal.journalType)?.label || glJournal.journalType },
          { label: "Reference", value: glJournal.reference },
          { label: "Narration", value: glJournal.narration },
          { label: isLandlordWorkspace ? "Owner" : "Landlord", value: glJournal.landlord?.landlordName || glJournal.landlord?.name },
          { label: "Property",  value: glJournal.property?.propertyName || glJournal.property?.name },
        ] : []}
        businessId={currentCompany?._id}
        sourceType="manual_adjustment"
        sourceId={glJournal?._id}
      />

    </DashboardLayout>
  );

};

export default JournalEntries;
